package posting

import (
	"context"
	"errors"
	"strconv"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Repo is the durable financial store. Everything it does is a statement against the iam_v2 financial
// ledgers; it contains no policy. The policy is in Gate, and the invariants are in the database.
type Repo struct{ pool *pgxpool.Pool }

// NewRepo wraps a pool.
func NewRepo(p *pgxpool.Pool) *Repo { return &Repo{pool: p} }

// Pool exposes the underlying pool for tests and for callers that own their own transaction.
func (r *Repo) Pool() *pgxpool.Pool { return r.pool }

// nullable renders "" as a SQL NULL so an unpinned optional identifier is stored as absent rather than as
// an empty string that a composite foreign key would then fail on for the wrong reason.
func nullable(s string) any {
	if s == "" {
		return nil
	}
	return s
}

// InsertPosting writes the posting row and its QUEUED outbox row in ONE transaction.
//
// The two must be atomic. A posting with no outbox row is money that was authorized and will never be
// sent; an outbox row with no posting is a worker looping on nothing. Because they commit together,
// neither state is reachable.
// The posting identifier is generated by the database, so no Go-side identifier can exist for a posting
// the database refused to accept.
func (r *Repo) InsertPosting(ctx context.Context, tx pgx.Tx, p Pinned) (string, error) {
	var id string
	if err := tx.QueryRow(ctx, `
INSERT INTO iam_v2.pms_postings
  (tenant_id, site_id, pms_interface_id, settlement_id, purchase_id, stay_id, folio_id,
   posting_interface_revision_id, secret_generation_id, posting_type,
   amount_minor, currency, currency_exponent, idempotency_key)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'CHARGE',$10,$11,$12,$13)
RETURNING id::text`,
		p.TenantID, p.SiteID, p.PMSInterfaceID, p.SettlementID, p.PurchaseID, p.StayID, p.FolioID,
		p.PostingInterfaceRevisionID, nullable(p.SecretGenerationID),
		p.AmountMinor, p.Currency, p.CurrencyExponent, p.IdempotencyKey).Scan(&id); err != nil {
		return "", classify(err)
	}
	if _, err := tx.Exec(ctx, `
INSERT INTO iam_v2.posting_outbox (tenant_id, site_id, pms_interface_id, posting_id, state)
VALUES ($1,$2,$3,$4,'QUEUED')`, p.TenantID, p.SiteID, p.PMSInterfaceID, id); err != nil {
		return "", classify(err)
	}
	return id, nil
}

// Claim is one unit of outbox work, claimed by exactly one worker.
type Claim struct {
	OutboxID  string
	PostingID string
	Pinned    Pinned
	AttemptNo int
}

// ClaimNext claims at most one QUEUED posting for ONE interface and marks it IN_FLIGHT.
//
// FOR UPDATE SKIP LOCKED gives per-interface lanes their independence: a worker for interface A never waits
// on a row another worker already holds, and a stuck lane cannot stall a healthy one. The partial unique
// index outbox_one_active then guarantees the thing SKIP LOCKED alone would not — that one posting can
// never have two ACTIVE outbox rows, so it cannot be executed twice even by two workers that both believe
// they own it.
//
// It returns (nil, nil) when the lane has nothing to do.
func (r *Repo) ClaimNext(ctx context.Context, tx pgx.Tx, tenantID, siteID, interfaceID string) (*Claim, error) {
	var c Claim
	err := tx.QueryRow(ctx, `
WITH claimed AS (
  SELECT o.id
    FROM iam_v2.posting_outbox o
   WHERE o.tenant_id = $1 AND o.site_id = $2 AND o.pms_interface_id = $3 AND o.state = 'QUEUED'
   ORDER BY o.id
     FOR UPDATE SKIP LOCKED
   LIMIT 1)
UPDATE iam_v2.posting_outbox o
   SET state = 'IN_FLIGHT'
  FROM claimed, iam_v2.pms_postings p
 WHERE o.id = claimed.id AND p.id = o.posting_id
RETURNING o.id::text, p.id::text, p.settlement_id::text, p.purchase_id::text, p.stay_id::text,
          p.folio_id::text, p.posting_interface_revision_id::text,
          coalesce(p.secret_generation_id::text,''), p.amount_minor, p.currency, p.currency_exponent,
          p.idempotency_key`,
		tenantID, siteID, interfaceID).Scan(
		&c.OutboxID, &c.PostingID, &c.Pinned.SettlementID, &c.Pinned.PurchaseID, &c.Pinned.StayID,
		&c.Pinned.FolioID, &c.Pinned.PostingInterfaceRevisionID, &c.Pinned.SecretGenerationID,
		&c.Pinned.AmountMinor, &c.Pinned.Currency, &c.Pinned.CurrencyExponent, &c.Pinned.IdempotencyKey)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, classify(err)
	}
	c.Pinned.TenantID, c.Pinned.SiteID, c.Pinned.PMSInterfaceID = tenantID, siteID, interfaceID

	// The remaining pinned fields are read from the objects the posting already points at. This is reading
	// the pin, not re-resolving it: package revision and settlement mapping are the ones this purchase was
	// created against, and posting_code is the mapping's own configured value.
	if err := tx.QueryRow(ctx, `
SELECT pu.package_revision_id::text, coalesce(pu.settlement_mapping_id::text,''),
       coalesce(sm.posting_code,''), pu.state
  FROM iam_v2.purchases pu
  LEFT JOIN iam_v2.package_settlement_mappings sm ON sm.id = pu.settlement_mapping_id
 WHERE pu.tenant_id = $1 AND pu.site_id = $2 AND pu.id = $3`,
		tenantID, siteID, c.Pinned.PurchaseID).Scan(
		&c.Pinned.PackageRevisionID, &c.Pinned.SettlementMappingID,
		&c.Pinned.PostingCode, &c.Pinned.ExpectPurchaseState); err != nil {
		return nil, classify(err)
	}
	// attempt numbering continues the durable ledger, never a counter held in memory
	if err := tx.QueryRow(ctx,
		`SELECT coalesce(max(attempt_no),0)+1 FROM iam_v2.posting_attempts WHERE internal_posting_id = $1`,
		c.PostingID).Scan(&c.AttemptNo); err != nil {
		return nil, classify(err)
	}
	return &c, nil
}

// ReleaseClaim puts a claimed row back to QUEUED. Used when the lane declines to execute (DARK, or an
// evidence refusal that a later operator action could legitimately resolve).
func (r *Repo) ReleaseClaim(ctx context.Context, tx pgx.Tx, outboxID string) error {
	_, err := tx.Exec(ctx, `UPDATE iam_v2.posting_outbox SET state='QUEUED' WHERE id=$1`, outboxID)
	return classify(err)
}

// FinishClaim marks an outbox row terminal (DONE) or parks it for recovery (HELD_RECOVERY).
func (r *Repo) FinishClaim(ctx context.Context, tx pgx.Tx, outboxID, state string) error {
	_, err := tx.Exec(ctx, `UPDATE iam_v2.posting_outbox SET state=$2 WHERE id=$1`, outboxID, state)
	return classify(err)
}

// AllocatePNumber consumes exactly one durable protocol-attempt reference for an interface.
func (r *Repo) AllocatePNumber(ctx context.Context, tx pgx.Tx, tenantID, siteID, interfaceID string) (int64, error) {
	var p int64
	if err := tx.QueryRow(ctx, `SELECT iam_v2.allocate_p_number($1,$2,$3)`,
		tenantID, siteID, interfaceID).Scan(&p); err != nil {
		return 0, classify(err)
	}
	return p, nil
}

// InsertAttempt records a transmission attempt as SENDING. The database refuses it outright unless RN and
// G# are present and wire-safe, the attempt number continues the sequence, and any retry after an UNKNOWN
// or ACKED attempt carries an audited authorization.
func (r *Repo) InsertAttempt(ctx context.Context, tx pgx.Tx, p Pinned, postingID string, attemptNo int, pNumber int64) (string, error) {
	var id string
	if err := tx.QueryRow(ctx, `
INSERT INTO iam_v2.posting_attempts
  (tenant_id, site_id, internal_posting_id, pms_interface_id, attempt_no, p_number, rn, g_number, sent_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8, now())
RETURNING id::text`,
		p.TenantID, p.SiteID, postingID, p.PMSInterfaceID, attemptNo,
		// p_number is a text column: render the allocated integer here rather than casting in SQL, so the
		// value that is stored is byte-for-byte the value that goes on the wire.
		strconv.FormatInt(pNumber, 10), p.RN, p.GNumber).Scan(&id); err != nil {
		return "", classify(err)
	}
	return id, nil
}

// SettleAttempt applies the ONE terminal outcome an attempt is allowed to reach. The database enforces the
// one-way transition; this just names it.
func (r *Repo) SettleAttempt(ctx context.Context, tx pgx.Tx, attemptID, outcome, asStatus string) error {
	_, err := tx.Exec(ctx, `
UPDATE iam_v2.posting_attempts
   SET outcome = $2, pa_as_status = $3, response_at = now()
 WHERE id = $1`, attemptID, outcome, nullable(asStatus))
	return classify(err)
}

// AppendAttemptEvent writes one row to the fully append-only attempt-event ledger.
//
// detail is a JSON document and it must never carry a secret, a card number or guest PII. Callers in this
// package pass only protocol facts: the record id, the AS value, the classification.
func (r *Repo) AppendAttemptEvent(ctx context.Context, tx pgx.Tx, p Pinned, attemptID, eventType, detailJSON string) error {
	if detailJSON == "" {
		detailJSON = "{}"
	}
	_, err := tx.Exec(ctx, `
INSERT INTO iam_v2.posting_attempt_events (tenant_id, site_id, posting_attempt_id, event_type, detail)
VALUES ($1,$2,$3,$4,$5::jsonb)`, p.TenantID, p.SiteID, attemptID, eventType, detailJSON)
	return classify(err)
}

// RecordReview routes a manual-review decision through the single controlled writer.
//
// expectedVersion is the review version the reviewer actually saw. Passing it is what turns "two operators
// clicked at the same time" into a refusal for the second one instead of two decisions on one charge.
// reversalAmount is meaningful ONLY for CREATE_REVERSAL, where nil means "reverse the whole charge" and a
// value records a partial correction. Every other action must pass nil; the database refuses an amount it
// has no use for rather than ignoring it.
func (r *Repo) RecordReview(ctx context.Context, postingID, action, actor, reason, evidenceJSON string, expectedVersion *int, reversalAmount *int64) (string, error) {
	if evidenceJSON == "" {
		evidenceJSON = "{}"
	}
	var id string
	err := r.pool.QueryRow(ctx,
		`SELECT iam_v2.record_posting_review_action($1,$2,$3,$4,$5::jsonb,$6,$7)::text`,
		postingID, action, actor, reason, evidenceJSON, expectedVersion, reversalAmount).Scan(&id)
	if err != nil {
		return "", classify(err)
	}
	return id, nil
}

// State is one row of the derived read model. Nothing here is stored; every field is computed by the view
// from the posting, outbox, attempt and review ledgers.
type State struct {
	PostingID                  string
	ExecutionState             string
	LatestAttemptNo            *int
	LatestPNumber              *string
	OutboxState                *string
	HasUnknownHistory          bool
	AwaitingManualReview       bool
	TerminalReviewAction       *string
	ReviewVersion              *int
	AttemptCount               int64
	UnknownAttemptCount        int64
	LatestPAStatusValue        *string
	RetryAuthorizationConsumed bool
	FreshnessBlock             *string
}

// LatestPAStatus returns the AS the PMS gave for the latest attempt, or "" when it gave none. It is a
// method rather than a bare pointer so a caller cannot accidentally treat "no answer" as an answer.
func (s State) LatestPAStatus() string {
	if s.LatestPAStatusValue == nil {
		return ""
	}
	return *s.LatestPAStatusValue
}

// ReadState reads the derived projection for one posting.
func (r *Repo) ReadState(ctx context.Context, postingID string) (State, error) {
	var s State
	err := r.pool.QueryRow(ctx, `
SELECT posting_id::text, execution_state, latest_attempt_no, latest_p_number, outbox_state,
       coalesce(has_unknown_history,false), coalesce(awaiting_manual_review,false),
       terminal_review_action, review_version, coalesce(attempt_count,0), coalesce(unknown_attempt_count,0),
       latest_pa_as_status, coalesce(retry_authorization_consumed,false), freshness_block
  FROM iam_v2.posting_execution_state WHERE posting_id = $1`, postingID).Scan(
		&s.PostingID, &s.ExecutionState, &s.LatestAttemptNo, &s.LatestPNumber, &s.OutboxState,
		&s.HasUnknownHistory, &s.AwaitingManualReview, &s.TerminalReviewAction, &s.ReviewVersion,
		&s.AttemptCount, &s.UnknownAttemptCount,
		&s.LatestPAStatusValue, &s.RetryAuthorizationConsumed, &s.FreshnessBlock)
	if err != nil {
		return State{}, classify(err)
	}
	return s, nil
}

// classify turns a database refusal into the typed financial code that names it, so a caller and an
// operator see the same vocabulary whether the refusal came from Gate or from a trigger.
func classify(err error) error {
	if err == nil {
		return nil
	}
	msg := err.Error()
	for _, m := range []struct {
		needle string
		code   Code
	}{
		{"FOLIO_STRATEGY_UNSET", ErrFolioStrategyUnset},
		{"POSTING_NOT_ALLOWED", ErrPostingNotAllowed},
		{"INTERFACE_CURRENCY_NOT_ONBOARDED", ErrInterfaceNoCurrency},
		{"POSTING_CURRENCY_MISMATCH", ErrCurrencyMismatch},
		{"PURCHASE_CURRENCY_MISMATCH", ErrCurrencyMismatch},
		{"PACKAGE_CURRENCY_MISMATCH", ErrCurrencyMismatch},
		{"POSTING_CURRENCY_UNSET", ErrCurrencyMismatch},
		{"PURCHASE_CURRENCY_UNSET", ErrCurrencyMismatch},
		{"PACKAGE_CURRENCY_UNSET", ErrCurrencyMismatch},
		{"attempt_rn_verified", ErrRNMissing},
		{"attempt_gnumber_verified", ErrGNumberMissing},
		{"attempt_rn_wire_safe", ErrRNNotWireSafe},
		{"attempt_gnumber_wire_safe", ErrGNumberNotWireSafe},
		{"attempt_pnumber_wire_safe", ErrWireFieldInvalid},
		{"ATTEMPT_IN_FLIGHT", ErrAlreadyInFlight},
		{"RETRY_REQUIRES_REVIEW", ErrRetryNotAuthed},
		{"ATTEMPT_SEQUENCE", ErrRetryNotAuthed},
		{"REVIEW_CONFLICT", ErrReviewConflict},
		{"REVIEW_ALREADY_DECIDED", ErrReviewConflict},
		{"REVIEW_VERSION_STALE", ErrReviewStale},
		{"REVIEW_ACTION_UNKNOWN", ErrReviewConflict},
		{"REVIEW_WRITER_ONLY", ErrReviewConflict},
		{"REVIEW_REVERSAL_REFUSED", ErrReviewConflict},
		{"REVERSAL_NOT_EXECUTABLE", ErrReversalDisabled},
		{"REVERSAL_WRITER_ONLY", ErrReversalDisabled},
		{"REVERSAL_EXCEEDS_CHARGE", ErrReviewConflict},
	} {
		if contains(msg, m.needle) {
			return &Error{Code: m.code, Msg: m.needle}
		}
	}
	// Unrecognised: keep the database's own first line. It names the constraint or the SQLSTATE, which is
	// what an operator needs, and it carries no guest PII of its own - the financial ledgers store
	// identifiers and integer amounts, not names or card data.
	if i := indexByte(msg, 10); i >= 0 {
		msg = msg[:i]
	}
	return &Error{Code: ErrRepo, Msg: msg}
}

func indexByte(s string, b byte) int {
	for i := 0; i < len(s); i++ {
		if s[i] == b {
			return i
		}
	}
	return -1
}

func contains(hay, needle string) bool {
	for i := 0; i+len(needle) <= len(hay); i++ {
		if hay[i:i+len(needle)] == needle {
			return true
		}
	}
	return false
}
