package main

// THE WORDS OF THE "AVAILABLE PACKAGES" PANEL, AS A PORTAL-ONLY TABLE.
//
// The panel exists only when the Phase-2 commerce surface is switched on, which it is not in production. Its
// wording is kept OUT of builtinStrings on purpose: that dictionary is the one a hotel may override, key by
// key, and edged caps a hotel's overrides at portaldesign.MaxTranslationKeys per language -- a hotel adding a
// language of its own can only translate the whole portal if the portal ships no more keys than that. These
// strings are therefore shipped complete in the six built-in languages, rendered into the page for the guest's
// language with English underneath, and not offered in Hotel Admin (strings.ts) for override.
//
// Placeholders: {n} a number, {v} an already-formatted value, {date} a date in the device's own format.
// End modes are the codes internal/iamv2 defines (commerce_duration.go); a code this table does not know is
// shown as cx.end.other rather than as the code.

// commerceKeys is every key the panel reads. A test holds every language to it.
var commerceKeys = []string{
	"cx.title", "cx.loading", "cx.unavailable", "cx.none", "cx.expired", "cx.default",
	"cx.down", "cx.up", "cx.data", "cx.time", "cx.devices", "cx.ends", "cx.unlimited",
	"cx.b", "cx.kb", "cx.mb", "cx.gb", "cx.tb",
	"cx.end.MANUAL_END", "cx.end.VALIDITY_WINDOW", "cx.end.FIXED_AT", "cx.end.AT_CHECKOUT",
	"cx.end.GRACE_AFTER_CHECKOUT", "cx.end.EARLIEST_OF_FIXED_AND_CHECKOUT", "cx.end.REST_OF_STAY", "cx.end.other",
	"cx.select", "cx.confirm.title", "cx.free", "cx.expires", "cx.confirm", "cx.active.title", "cx.active",
}

var commerceStrings = map[string]map[string]string{
	"en": {
		"cx.title":                              "Available packages",
		"cx.loading":                            "Loading…",
		"cx.unavailable":                        "This option is unavailable right now.",
		"cx.none":                               "No packages are available for you right now.",
		"cx.expired":                            "That offer expired or is no longer available.",
		"cx.default":                            "Package",
		"cx.down":                               "{n} Mbps down",
		"cx.up":                                 "{n} up",
		"cx.data":                               "Data: {v}",
		"cx.time":                               "Time: {v}",
		"cx.devices":                            "Devices: {n}",
		"cx.ends":                               "Ends: {v}",
		"cx.unlimited":                          "unlimited",
		"cx.b":                                  "{n} B",
		"cx.kb":                                 "{n} KB",
		"cx.mb":                                 "{n} MB",
		"cx.gb":                                 "{n} GB",
		"cx.tb":                                 "{n} TB",
		"cx.end.MANUAL_END":                     "no fixed end",
		"cx.end.VALIDITY_WINDOW":                "after the package time",
		"cx.end.FIXED_AT":                       "on a set date",
		"cx.end.AT_CHECKOUT":                    "at checkout",
		"cx.end.GRACE_AFTER_CHECKOUT":           "shortly after checkout",
		"cx.end.EARLIEST_OF_FIXED_AND_CHECKOUT": "on a set date or at checkout, whichever is first",
		"cx.end.REST_OF_STAY":                   "at the end of your stay",
		"cx.end.other":                          "as set by the hotel",
		"cx.select":                             "Select",
		"cx.confirm.title":                      "Confirm your package",
		"cx.free":                               "free",
		"cx.expires":                            "Offer expires: {date}",
		"cx.confirm":                            "Confirm",
		"cx.active.title":                       "Package active",
		"cx.active":                             "Your package is now active. Enjoy your connection.",
	},
	"ar": {
		"cx.title":                              "الباقات المتاحة",
		"cx.loading":                            "جارٍ التحميل…",
		"cx.unavailable":                        "هذا الخيار غير متاح حالياً.",
		"cx.none":                               "لا توجد باقات متاحة لك حالياً.",
		"cx.expired":                            "انتهت صلاحية هذا العرض أو لم يعد متاحاً.",
		"cx.default":                            "باقة",
		"cx.down":                               "تنزيل {n} ميغابت/ث",
		"cx.up":                                 "رفع {n}",
		"cx.data":                               "البيانات: {v}",
		"cx.time":                               "المدة: {v}",
		"cx.devices":                            "الأجهزة: {n}",
		"cx.ends":                               "تنتهي: {v}",
		"cx.unlimited":                          "غير محدودة",
		"cx.b":                                  "{n} بايت",
		"cx.kb":                                 "{n} ك.بايت",
		"cx.mb":                                 "{n} م.بايت",
		"cx.gb":                                 "{n} غ.بايت",
		"cx.tb":                                 "{n} ت.بايت",
		"cx.end.MANUAL_END":                     "بدون موعد انتهاء محدد",
		"cx.end.VALIDITY_WINDOW":                "بعد انقضاء مدة الباقة",
		"cx.end.FIXED_AT":                       "في تاريخ محدد",
		"cx.end.AT_CHECKOUT":                    "عند المغادرة",
		"cx.end.GRACE_AFTER_CHECKOUT":           "بعد المغادرة بوقت قصير",
		"cx.end.EARLIEST_OF_FIXED_AND_CHECKOUT": "في تاريخ محدد أو عند المغادرة، أيهما أقرب",
		"cx.end.REST_OF_STAY":                   "في نهاية إقامتك",
		"cx.end.other":                          "حسب إعدادات الفندق",
		"cx.select":                             "اختيار",
		"cx.confirm.title":                      "تأكيد باقتك",
		"cx.free":                               "مجانية",
		"cx.expires":                            "ينتهي العرض: {date}",
		"cx.confirm":                            "تأكيد",
		"cx.active.title":                       "الباقة مفعّلة",
		"cx.active":                             "باقتك مفعّلة الآن. استمتع باتصالك.",
	},
	"de": {
		"cx.title":                              "Verfügbare Pakete",
		"cx.loading":                            "Wird geladen…",
		"cx.unavailable":                        "Diese Option ist gerade nicht verfügbar.",
		"cx.none":                               "Für Sie sind gerade keine Pakete verfügbar.",
		"cx.expired":                            "Dieses Angebot ist abgelaufen oder nicht mehr verfügbar.",
		"cx.default":                            "Paket",
		"cx.down":                               "{n} Mbit/s Download",
		"cx.up":                                 "{n} Upload",
		"cx.data":                               "Daten: {v}",
		"cx.time":                               "Dauer: {v}",
		"cx.devices":                            "Geräte: {n}",
		"cx.ends":                               "Endet: {v}",
		"cx.unlimited":                          "unbegrenzt",
		"cx.b":                                  "{n} Byte",
		"cx.kb":                                 "{n} KB",
		"cx.mb":                                 "{n} MB",
		"cx.gb":                                 "{n} GB",
		"cx.tb":                                 "{n} TB",
		"cx.end.MANUAL_END":                     "ohne festes Ende",
		"cx.end.VALIDITY_WINDOW":                "nach Ablauf der Paketdauer",
		"cx.end.FIXED_AT":                       "an einem festen Datum",
		"cx.end.AT_CHECKOUT":                    "beim Check-out",
		"cx.end.GRACE_AFTER_CHECKOUT":           "kurz nach dem Check-out",
		"cx.end.EARLIEST_OF_FIXED_AND_CHECKOUT": "an einem festen Datum oder beim Check-out, je nachdem, was zuerst eintritt",
		"cx.end.REST_OF_STAY":                   "am Ende Ihres Aufenthalts",
		"cx.end.other":                          "wie vom Hotel festgelegt",
		"cx.select":                             "Auswählen",
		"cx.confirm.title":                      "Paket bestätigen",
		"cx.free":                               "kostenlos",
		"cx.expires":                            "Angebot gültig bis: {date}",
		"cx.confirm":                            "Bestätigen",
		"cx.active.title":                       "Paket aktiv",
		"cx.active":                             "Ihr Paket ist jetzt aktiv. Viel Spaß mit Ihrer Verbindung.",
	},
	"fr": {
		"cx.title":                              "Forfaits disponibles",
		"cx.loading":                            "Chargement…",
		"cx.unavailable":                        "Cette option n'est pas disponible pour le moment.",
		"cx.none":                               "Aucun forfait n'est disponible pour vous pour le moment.",
		"cx.expired":                            "Cette offre a expiré ou n'est plus disponible.",
		"cx.default":                            "Forfait",
		"cx.down":                               "{n} Mbit/s en réception",
		"cx.up":                                 "{n} en envoi",
		"cx.data":                               "Données : {v}",
		"cx.time":                               "Durée : {v}",
		"cx.devices":                            "Appareils : {n}",
		"cx.ends":                               "Fin : {v}",
		"cx.unlimited":                          "illimité",
		"cx.b":                                  "{n} o",
		"cx.kb":                                 "{n} Ko",
		"cx.mb":                                 "{n} Mo",
		"cx.gb":                                 "{n} Go",
		"cx.tb":                                 "{n} To",
		"cx.end.MANUAL_END":                     "sans date de fin",
		"cx.end.VALIDITY_WINDOW":                "à la fin de la durée du forfait",
		"cx.end.FIXED_AT":                       "à une date fixée",
		"cx.end.AT_CHECKOUT":                    "au départ",
		"cx.end.GRACE_AFTER_CHECKOUT":           "peu après le départ",
		"cx.end.EARLIEST_OF_FIXED_AND_CHECKOUT": "à une date fixée ou au départ, selon ce qui arrive en premier",
		"cx.end.REST_OF_STAY":                   "à la fin de votre séjour",
		"cx.end.other":                          "selon les conditions de l'hôtel",
		"cx.select":                             "Choisir",
		"cx.confirm.title":                      "Confirmez votre forfait",
		"cx.free":                               "gratuit",
		"cx.expires":                            "Offre valable jusqu'au : {date}",
		"cx.confirm":                            "Confirmer",
		"cx.active.title":                       "Forfait activé",
		"cx.active":                             "Votre forfait est maintenant actif. Bonne connexion.",
	},
	"it": {
		"cx.title":                              "Pacchetti disponibili",
		"cx.loading":                            "Caricamento…",
		"cx.unavailable":                        "Questa opzione non è disponibile al momento.",
		"cx.none":                               "Al momento non ci sono pacchetti disponibili per te.",
		"cx.expired":                            "L'offerta è scaduta o non è più disponibile.",
		"cx.default":                            "Pacchetto",
		"cx.down":                               "{n} Mbit/s in download",
		"cx.up":                                 "{n} in upload",
		"cx.data":                               "Dati: {v}",
		"cx.time":                               "Durata: {v}",
		"cx.devices":                            "Dispositivi: {n}",
		"cx.ends":                               "Termina: {v}",
		"cx.unlimited":                          "illimitato",
		"cx.b":                                  "{n} byte",
		"cx.kb":                                 "{n} KB",
		"cx.mb":                                 "{n} MB",
		"cx.gb":                                 "{n} GB",
		"cx.tb":                                 "{n} TB",
		"cx.end.MANUAL_END":                     "senza una scadenza fissa",
		"cx.end.VALIDITY_WINDOW":                "al termine della durata del pacchetto",
		"cx.end.FIXED_AT":                       "in una data stabilita",
		"cx.end.AT_CHECKOUT":                    "al check-out",
		"cx.end.GRACE_AFTER_CHECKOUT":           "poco dopo il check-out",
		"cx.end.EARLIEST_OF_FIXED_AND_CHECKOUT": "in una data stabilita o al check-out, se prima",
		"cx.end.REST_OF_STAY":                   "alla fine del soggiorno",
		"cx.end.other":                          "come stabilito dall'hotel",
		"cx.select":                             "Scegli",
		"cx.confirm.title":                      "Conferma il pacchetto",
		"cx.free":                               "gratuito",
		"cx.expires":                            "L'offerta scade: {date}",
		"cx.confirm":                            "Conferma",
		"cx.active.title":                       "Pacchetto attivo",
		"cx.active":                             "Il tuo pacchetto è ora attivo. Buona navigazione.",
	},
	"ru": {
		"cx.title":                              "Доступные пакеты",
		"cx.loading":                            "Загрузка…",
		"cx.unavailable":                        "Этот вариант сейчас недоступен.",
		"cx.none":                               "Сейчас для вас нет доступных пакетов.",
		"cx.expired":                            "Срок предложения истёк, или оно больше недоступно.",
		"cx.default":                            "Пакет",
		"cx.down":                               "{n} Мбит/с на загрузку",
		"cx.up":                                 "{n} на отдачу",
		"cx.data":                               "Трафик: {v}",
		"cx.time":                               "Время: {v}",
		"cx.devices":                            "Устройства: {n}",
		"cx.ends":                               "Окончание: {v}",
		"cx.unlimited":                          "без ограничений",
		"cx.b":                                  "{n} Б",
		"cx.kb":                                 "{n} КБ",
		"cx.mb":                                 "{n} МБ",
		"cx.gb":                                 "{n} ГБ",
		"cx.tb":                                 "{n} ТБ",
		"cx.end.MANUAL_END":                     "без фиксированного окончания",
		"cx.end.VALIDITY_WINDOW":                "по истечении срока пакета",
		"cx.end.FIXED_AT":                       "в установленную дату",
		"cx.end.AT_CHECKOUT":                    "при выезде",
		"cx.end.GRACE_AFTER_CHECKOUT":           "вскоре после выезда",
		"cx.end.EARLIEST_OF_FIXED_AND_CHECKOUT": "в установленную дату или при выезде, что наступит раньше",
		"cx.end.REST_OF_STAY":                   "в конце проживания",
		"cx.end.other":                          "по правилам отеля",
		"cx.select":                             "Выбрать",
		"cx.confirm.title":                      "Подтвердите пакет",
		"cx.free":                               "бесплатно",
		"cx.expires":                            "Предложение действует до: {date}",
		"cx.confirm":                            "Подтвердить",
		"cx.active.title":                       "Пакет активен",
		"cx.active":                             "Ваш пакет активен. Приятного пользования.",
	},
}

// commerceWords is the panel's wording for one language: English underneath, the language over it. A
// language the portal does not ship (a hotel's own) reads English here; the hotel cannot override this table.
func commerceWords(code string) map[string]string {
	out := make(map[string]string, len(commerceKeys))
	for k, v := range commerceStrings["en"] {
		out[k] = v
	}
	for k, v := range commerceStrings[code] {
		if v != "" {
			out[k] = v
		}
	}
	return out
}
