package main

// THE WORDS OF EVERY PAGE AFTER THE SIGN-IN FORM, AND OF EVERY MESSAGE THE SERVER SENDS BACK.
//
// The sign-in form was the only part of the portal a guest could read in their own language. The package
// choice, "You're online", the device list, the social sign-in failure page and every refusal the server
// composed arrived in English -- and several of them as raw codes ("Voucher AUTH_DENIED.", "incorrect code").
// These keys close that gap. They are merged into builtinStrings at start-up, so there is still exactly one
// dictionary: the page renders it, /api/languages serves it, and Hotel Admin offers every key for override.
//
// Placeholders: {n} a number, {t} a duration, {date} a date. Each language places them where its grammar
// wants them. Units are abbreviated on purpose -- "{n} h" needs no plural rules, which Russian and Arabic
// would otherwise demand for every number.
//
// ROOM SIGN-IN STAYS VAGUE. err.room.credential and err.room.technical are the portal's translations of the
// server's closed set of sentences (pms_phase3.go). They say exactly what the English says -- never whether a
// room exists or who is in it -- and a wrong room and a wrong name still produce the same one.
var pageStrings = map[string]map[string]string{
	"en": {
		"brand.fallback":      "Guest Wi-Fi",
		"info.button":         "Device information",
		"info.none":           "Not detected",
		"notice.ended.data":   "Your Internet package has ended because the data allowance was used.",
		"notice.ended.time":   "Your Internet package has ended because the access time expired.",
		"err.room.credential": "The room number or guest detail you entered is incorrect. Check the room number and enter the full first name, family name, or reservation number.",
		"err.room.technical":  "We are unable to verify your stay right now. Please try again or contact Reception.",
		"err.wait":            "Too many attempts. Please wait and try again.",
		"err.wait.seconds":    "Too many attempts. Please wait {n} seconds and try again.",
		"err.attempts":        "Too many attempts. Please wait a minute and try again.",
		"err.voucher.empty":   "Please enter a voucher code.",
		"err.voucher.invalid": "That voucher code didn't work. Check the code and try again.",
		"err.voucher.devices": "This voucher has reached its device limit. Disconnect another device and try again.",
		"err.account.empty":   "Please enter your username and password.",
		"err.account.invalid": "The username or password is incorrect.",
		"err.account.devices": "This account has reached its device limit. Disconnect another device and try again.",
		"err.capacity":        "The guest network is at capacity. Please try again shortly.",
		"err.device.network":  "Your device isn't on the guest network.",
		"err.device.detect":   "Unable to detect your device address.",
		"err.service":         "Something went wrong. Please try again.",
		"err.packages.off":    "Internet packages are not available right now. Please ask reception.",
		"err.packages.none":   "No internet packages are available for you right now.",
		"err.package.gone":    "That package is not available. Please choose another.",
		"err.signin.again":    "Please sign in again.",
		"err.connect":         "We could not bring your device online. Please try again in a moment.",
		"err.otp.send":        "We couldn't send a code right now. Please try again, or choose another way to sign in.",
		"err.otp.dest":        "Please check what you entered and try again.",
		"err.otp.wait":        "Please wait a moment before asking for another code.",
		"err.otp.code":        "That code isn't right. Check it and try again.",
		"err.otp.expired":     "That code can no longer be used. Please ask for a new one.",
		"unit.mbps":           "{n} Mbps",
		"unit.h":              "{n} h",
		"unit.min":            "{n} min",
		"unit.d":              "{n} d",
		"pkg.title":           "Choose your package",
		"pkg.subtitle":        "You're signed in. Select a package to get online.",
		"pkg.default":         "Internet access",
		"online.title":        "You're online",
		"online.lead":         "Your device is connected to the internet.",
		"online.remaining":    "Time remaining",
		"online.unlimited":    "No time limit",
		"online.status":       "Status",
		"online.disconnect":   "Disconnect",
		"online.back":         "Back",
		"tl.left":             "{t} of internet time left",
		"tl.note":             "This counts down only while you are connected.",
		"tl.ends":             "Your access ends on {date}, whether or not the time is used.",
		"tl.none":             "No time",
		"dev.title":           "Your devices",
		"dev.lead":            "These are the devices using your internet access. Removing one frees its place for another device — nothing about your access changes, and the removed device can connect again at any time.",
		"dev.name":            "Device {n}",
		"dev.online":          "Connected now",
		"dev.offline":         "Not connected",
		"dev.lastused":        "Last used: {t}",
		"dev.justnow":         "just now",
		"dev.ago":             "{t} ago",
		"dev.remove":          "Remove this device",
		"dev.confirm":         "Remove device {n}? It will lose its place, and can connect again at any time.",
		"dev.yes":             "Remove",
		"dev.keep":            "Keep",
		"dev.inuse":           "In use right now, so it can’t be removed. Disconnect it from the Wi‑Fi first.",
		"dev.cannot":          "This device can’t be removed right now.",
		"dev.refused":         "That didn’t work. Please try again in a moment.",
		"dev.removed":         "That device has been removed and its place is free. It can connect again at any time.",
		"errpage.title":       "Sign-in didn't work",
		"errpage.social":      "We couldn't finish signing you in with that account. Please try again, or choose another way to sign in.",
		"errpage.back":        "Back to sign-in",
	},
	"ar": {
		"brand.fallback":      "شبكة الضيوف اللاسلكية",
		"info.button":         "معلومات الجهاز",
		"info.none":           "لم يتم التعرّف عليه",
		"notice.ended.data":   "انتهت باقة الإنترنت الخاصة بك لأنه تم استهلاك حد البيانات المسموح به.",
		"notice.ended.time":   "انتهت باقة الإنترنت الخاصة بك لانتهاء مدة الاستخدام.",
		"err.room.credential": "رقم الغرفة أو بيانات الضيف التي أدخلتها غير صحيحة. تحقّق من رقم الغرفة وأدخل الاسم الأول كاملاً أو اسم العائلة أو رقم الحجز.",
		"err.room.technical":  "يتعذّر علينا التحقق من إقامتك في الوقت الحالي. يرجى المحاولة مرة أخرى أو التواصل مع مكتب الاستقبال.",
		"err.wait":            "محاولات كثيرة جداً. يرجى الانتظار ثم المحاولة مرة أخرى.",
		"err.wait.seconds":    "محاولات كثيرة جداً. يرجى الانتظار {n} ثانية ثم المحاولة مرة أخرى.",
		"err.attempts":        "محاولات كثيرة جداً. يرجى الانتظار دقيقة ثم المحاولة مرة أخرى.",
		"err.voucher.empty":   "يرجى إدخال رمز القسيمة.",
		"err.voucher.invalid": "رمز القسيمة غير صالح. تحقّق من الرمز وحاول مرة أخرى.",
		"err.voucher.devices": "وصلت هذه القسيمة إلى الحد الأقصى لعدد الأجهزة. افصل جهازاً آخر ثم حاول مرة أخرى.",
		"err.account.empty":   "يرجى إدخال اسم المستخدم وكلمة المرور.",
		"err.account.invalid": "اسم المستخدم أو كلمة المرور غير صحيحة.",
		"err.account.devices": "وصل هذا الحساب إلى الحد الأقصى لعدد الأجهزة. افصل جهازاً آخر ثم حاول مرة أخرى.",
		"err.capacity":        "شبكة الضيوف ممتلئة حالياً. يرجى المحاولة بعد قليل.",
		"err.device.network":  "جهازك غير متصل بشبكة الضيوف.",
		"err.device.detect":   "تعذّر التعرّف على عنوان جهازك.",
		"err.service":         "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
		"err.packages.off":    "باقات الإنترنت غير متاحة حالياً. يرجى مراجعة مكتب الاستقبال.",
		"err.packages.none":   "لا توجد باقات إنترنت متاحة لك حالياً.",
		"err.package.gone":    "هذه الباقة غير متاحة. يرجى اختيار باقة أخرى.",
		"err.signin.again":    "يرجى تسجيل الدخول مرة أخرى.",
		"err.connect":         "تعذّر توصيل جهازك بالإنترنت. يرجى المحاولة بعد لحظات.",
		"err.otp.send":        "تعذّر إرسال الرمز الآن. يرجى المحاولة مرة أخرى أو اختيار طريقة أخرى لتسجيل الدخول.",
		"err.otp.dest":        "يرجى التحقق مما أدخلته والمحاولة مرة أخرى.",
		"err.otp.wait":        "يرجى الانتظار قليلاً قبل طلب رمز جديد.",
		"err.otp.code":        "الرمز غير صحيح. تحقّق منه وحاول مرة أخرى.",
		"err.otp.expired":     "لم يعد بالإمكان استخدام هذا الرمز. يرجى طلب رمز جديد.",
		"unit.mbps":           "{n} ميغابت/ث",
		"unit.h":              "{n} س",
		"unit.min":            "{n} د",
		"unit.d":              "{n} يوم",
		"pkg.title":           "اختر باقتك",
		"pkg.subtitle":        "تم تسجيل دخولك. اختر باقة للاتصال بالإنترنت.",
		"pkg.default":         "الوصول إلى الإنترنت",
		"online.title":        "أنت متصل بالإنترنت",
		"online.lead":         "جهازك متصل بالإنترنت الآن.",
		"online.remaining":    "الوقت المتبقي",
		"online.unlimited":    "بدون حد زمني",
		"online.status":       "الحالة",
		"online.disconnect":   "قطع الاتصال",
		"online.back":         "رجوع",
		"tl.left":             "متبقٍّ لك {t} من وقت الإنترنت",
		"tl.note":             "يُحتسب هذا الوقت فقط أثناء اتصالك.",
		"tl.ends":             "ينتهي وصولك في {date}، سواء استُخدم الوقت أم لا.",
		"tl.none":             "لا يوجد وقت",
		"dev.title":           "أجهزتك",
		"dev.lead":            "هذه هي الأجهزة التي تستخدم اتصالك بالإنترنت. إزالة جهاز تُفسح مكانه لجهاز آخر — لا يتغيّر شيء في وصولك، ويمكن للجهاز المُزال الاتصال مجدداً في أي وقت.",
		"dev.name":            "الجهاز {n}",
		"dev.online":          "متصل الآن",
		"dev.offline":         "غير متصل",
		"dev.lastused":        "آخر استخدام: {t}",
		"dev.justnow":         "الآن",
		"dev.ago":             "منذ {t}",
		"dev.remove":          "إزالة هذا الجهاز",
		"dev.confirm":         "إزالة الجهاز {n}؟ سيفقد مكانه، ويمكنه الاتصال مجدداً في أي وقت.",
		"dev.yes":             "إزالة",
		"dev.keep":            "إبقاء",
		"dev.inuse":           "هذا الجهاز قيد الاستخدام الآن، لذا لا يمكن إزالته. افصله عن الشبكة اللاسلكية أولاً.",
		"dev.cannot":          "لا يمكن إزالة هذا الجهاز الآن.",
		"dev.refused":         "لم تنجح العملية. يرجى المحاولة بعد لحظات.",
		"dev.removed":         "تمت إزالة الجهاز وأصبح مكانه متاحاً. يمكنه الاتصال مجدداً في أي وقت.",
		"errpage.title":       "لم يكتمل تسجيل الدخول",
		"errpage.social":      "تعذّر إكمال تسجيل دخولك بهذا الحساب. يرجى المحاولة مرة أخرى أو اختيار طريقة أخرى لتسجيل الدخول.",
		"errpage.back":        "العودة إلى تسجيل الدخول",
	},
	"de": {
		"brand.fallback":      "Gäste-WLAN",
		"info.button":         "Geräteinformationen",
		"info.none":           "Nicht erkannt",
		"notice.ended.data":   "Ihr Internetpaket ist beendet, weil das Datenvolumen aufgebraucht ist.",
		"notice.ended.time":   "Ihr Internetpaket ist beendet, weil die Nutzungszeit abgelaufen ist.",
		"err.room.credential": "Die eingegebene Zimmernummer oder Gästeangabe ist nicht korrekt. Prüfen Sie die Zimmernummer und geben Sie den vollständigen Vornamen, Nachnamen oder die Reservierungsnummer ein.",
		"err.room.technical":  "Wir können Ihren Aufenthalt gerade nicht überprüfen. Bitte versuchen Sie es erneut oder wenden Sie sich an die Rezeption.",
		"err.wait":            "Zu viele Versuche. Bitte warten Sie kurz und versuchen Sie es dann erneut.",
		"err.wait.seconds":    "Zu viele Versuche. Bitte warten Sie {n} Sekunden und versuchen Sie es dann erneut.",
		"err.attempts":        "Zu viele Versuche. Bitte warten Sie eine Minute und versuchen Sie es dann erneut.",
		"err.voucher.empty":   "Bitte geben Sie einen Gutscheincode ein.",
		"err.voucher.invalid": "Dieser Gutscheincode hat nicht funktioniert. Prüfen Sie den Code und versuchen Sie es erneut.",
		"err.voucher.devices": "Dieser Gutschein hat die maximale Anzahl an Geräten erreicht. Trennen Sie ein anderes Gerät und versuchen Sie es erneut.",
		"err.account.empty":   "Bitte geben Sie Benutzername und Passwort ein.",
		"err.account.invalid": "Benutzername oder Passwort ist falsch.",
		"err.account.devices": "Dieses Konto hat die maximale Anzahl an Geräten erreicht. Trennen Sie ein anderes Gerät und versuchen Sie es erneut.",
		"err.capacity":        "Das Gästenetz ist gerade ausgelastet. Bitte versuchen Sie es in Kürze erneut.",
		"err.device.network":  "Ihr Gerät ist nicht mit dem Gästenetz verbunden.",
		"err.device.detect":   "Die Adresse Ihres Geräts konnte nicht ermittelt werden.",
		"err.service":         "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.",
		"err.packages.off":    "Internetpakete sind gerade nicht verfügbar. Bitte wenden Sie sich an die Rezeption.",
		"err.packages.none":   "Für Sie sind gerade keine Internetpakete verfügbar.",
		"err.package.gone":    "Dieses Paket ist nicht verfügbar. Bitte wählen Sie ein anderes.",
		"err.signin.again":    "Bitte melden Sie sich erneut an.",
		"err.connect":         "Ihr Gerät konnte nicht online gebracht werden. Bitte versuchen Sie es gleich noch einmal.",
		"err.otp.send":        "Der Code konnte gerade nicht gesendet werden. Bitte versuchen Sie es erneut oder wählen Sie eine andere Anmeldeart.",
		"err.otp.dest":        "Bitte prüfen Sie Ihre Eingabe und versuchen Sie es erneut.",
		"err.otp.wait":        "Bitte warten Sie einen Moment, bevor Sie einen neuen Code anfordern.",
		"err.otp.code":        "Dieser Code ist nicht korrekt. Prüfen Sie ihn und versuchen Sie es erneut.",
		"err.otp.expired":     "Dieser Code kann nicht mehr verwendet werden. Bitte fordern Sie einen neuen an.",
		"unit.mbps":           "{n} Mbit/s",
		"unit.h":              "{n} Std.",
		"unit.min":            "{n} Min.",
		"unit.d":              "{n} Tg.",
		"pkg.title":           "Wählen Sie Ihr Paket",
		"pkg.subtitle":        "Sie sind angemeldet. Wählen Sie ein Paket, um online zu gehen.",
		"pkg.default":         "Internetzugang",
		"online.title":        "Sie sind online",
		"online.lead":         "Ihr Gerät ist mit dem Internet verbunden.",
		"online.remaining":    "Verbleibende Zeit",
		"online.unlimited":    "Ohne Zeitlimit",
		"online.status":       "Verbindungsstatus",
		"online.disconnect":   "Trennen",
		"online.back":         "Zurück",
		"tl.left":             "Noch {t} Internetzeit",
		"tl.note":             "Die Zeit läuft nur, solange Sie verbunden sind.",
		"tl.ends":             "Ihr Zugang endet am {date}, unabhängig davon, ob die Zeit genutzt wurde.",
		"tl.none":             "Keine Zeit",
		"dev.title":           "Ihre Geräte",
		"dev.lead":            "Diese Geräte nutzen Ihren Internetzugang. Wenn Sie eines entfernen, wird sein Platz für ein anderes Gerät frei — an Ihrem Zugang ändert sich nichts, und das entfernte Gerät kann sich jederzeit wieder verbinden.",
		"dev.name":            "Gerät {n}",
		"dev.online":          "Jetzt verbunden",
		"dev.offline":         "Nicht verbunden",
		"dev.lastused":        "Zuletzt genutzt: {t}",
		"dev.justnow":         "gerade eben",
		"dev.ago":             "vor {t}",
		"dev.remove":          "Dieses Gerät entfernen",
		"dev.confirm":         "Gerät {n} entfernen? Es verliert seinen Platz und kann sich jederzeit wieder verbinden.",
		"dev.yes":             "Entfernen",
		"dev.keep":            "Behalten",
		"dev.inuse":           "Wird gerade verwendet und kann daher nicht entfernt werden. Trennen Sie es zuerst vom WLAN.",
		"dev.cannot":          "Dieses Gerät kann gerade nicht entfernt werden.",
		"dev.refused":         "Das hat nicht geklappt. Bitte versuchen Sie es gleich noch einmal.",
		"dev.removed":         "Das Gerät wurde entfernt und sein Platz ist frei. Es kann sich jederzeit wieder verbinden.",
		"errpage.title":       "Anmeldung nicht abgeschlossen",
		"errpage.social":      "Die Anmeldung mit diesem Konto konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut oder wählen Sie eine andere Anmeldeart.",
		"errpage.back":        "Zurück zur Anmeldung",
	},
	"fr": {
		"brand.fallback":      "Wi-Fi invités",
		"info.button":         "Informations sur l'appareil",
		"info.none":           "Non détecté",
		"notice.ended.data":   "Votre forfait Internet a pris fin car le volume de données a été épuisé.",
		"notice.ended.time":   "Votre forfait Internet a pris fin car la durée d'accès est écoulée.",
		"err.room.credential": "Le numéro de chambre ou l'information saisie est incorrect. Vérifiez le numéro de chambre et saisissez le prénom complet, le nom de famille ou le numéro de réservation.",
		"err.room.technical":  "Nous ne pouvons pas vérifier votre séjour pour le moment. Veuillez réessayer ou contacter la réception.",
		"err.wait":            "Trop de tentatives. Veuillez patienter, puis réessayer.",
		"err.wait.seconds":    "Trop de tentatives. Veuillez patienter {n} secondes, puis réessayer.",
		"err.attempts":        "Trop de tentatives. Veuillez patienter une minute, puis réessayer.",
		"err.voucher.empty":   "Veuillez saisir un code d'accès.",
		"err.voucher.invalid": "Ce code d'accès n'a pas fonctionné. Vérifiez-le et réessayez.",
		"err.voucher.devices": "Ce code d'accès a atteint son nombre maximal d'appareils. Déconnectez un autre appareil et réessayez.",
		"err.account.empty":   "Veuillez saisir votre nom d'utilisateur et votre mot de passe.",
		"err.account.invalid": "Le nom d'utilisateur ou le mot de passe est incorrect.",
		"err.account.devices": "Ce compte a atteint son nombre maximal d'appareils. Déconnectez un autre appareil et réessayez.",
		"err.capacity":        "Le réseau invités est complet pour le moment. Veuillez réessayer dans quelques instants.",
		"err.device.network":  "Votre appareil n'est pas connecté au réseau invités.",
		"err.device.detect":   "Impossible de détecter l'adresse de votre appareil.",
		"err.service":         "Un problème est survenu. Veuillez réessayer.",
		"err.packages.off":    "Les forfaits Internet ne sont pas disponibles pour le moment. Veuillez vous adresser à la réception.",
		"err.packages.none":   "Aucun forfait Internet n'est disponible pour vous pour le moment.",
		"err.package.gone":    "Ce forfait n'est pas disponible. Veuillez en choisir un autre.",
		"err.signin.again":    "Veuillez vous reconnecter.",
		"err.connect":         "Nous n'avons pas pu connecter votre appareil. Veuillez réessayer dans un instant.",
		"err.otp.send":        "Nous n'avons pas pu envoyer de code pour le moment. Veuillez réessayer ou choisir un autre moyen de connexion.",
		"err.otp.dest":        "Veuillez vérifier votre saisie et réessayer.",
		"err.otp.wait":        "Veuillez patienter un instant avant de demander un nouveau code.",
		"err.otp.code":        "Ce code n'est pas correct. Vérifiez-le et réessayez.",
		"err.otp.expired":     "Ce code ne peut plus être utilisé. Veuillez en demander un nouveau.",
		"unit.mbps":           "{n} Mbit/s",
		"unit.h":              "{n} h",
		"unit.min":            "{n} min",
		"unit.d":              "{n} j",
		"pkg.title":           "Choisissez votre forfait",
		"pkg.subtitle":        "Vous êtes connecté. Sélectionnez un forfait pour accéder à Internet.",
		"pkg.default":         "Accès Internet",
		"online.title":        "Vous êtes en ligne",
		"online.lead":         "Votre appareil est connecté à Internet.",
		"online.remaining":    "Temps restant",
		"online.unlimited":    "Sans limite de temps",
		"online.status":       "État de la connexion",
		"online.disconnect":   "Se déconnecter",
		"online.back":         "Retour",
		"tl.left":             "Il vous reste {t} de temps Internet",
		"tl.note":             "Ce temps ne s'écoule que lorsque vous êtes connecté.",
		"tl.ends":             "Votre accès prend fin le {date}, que le temps soit utilisé ou non.",
		"tl.none":             "Plus de temps",
		"dev.title":           "Vos appareils",
		"dev.lead":            "Voici les appareils qui utilisent votre accès Internet. En retirer un libère sa place pour un autre appareil — votre accès reste inchangé, et l'appareil retiré peut se reconnecter à tout moment.",
		"dev.name":            "Appareil {n}",
		"dev.online":          "Connecté",
		"dev.offline":         "Non connecté",
		"dev.lastused":        "Dernière utilisation : {t}",
		"dev.justnow":         "à l'instant",
		"dev.ago":             "il y a {t}",
		"dev.remove":          "Retirer cet appareil",
		"dev.confirm":         "Retirer l'appareil {n} ? Il perdra sa place et pourra se reconnecter à tout moment.",
		"dev.yes":             "Retirer",
		"dev.keep":            "Conserver",
		"dev.inuse":           "Cet appareil est en cours d'utilisation et ne peut pas être retiré. Déconnectez-le d'abord du Wi-Fi.",
		"dev.cannot":          "Cet appareil ne peut pas être retiré pour le moment.",
		"dev.refused":         "Cela n'a pas fonctionné. Veuillez réessayer dans un instant.",
		"dev.removed":         "L'appareil a été retiré et sa place est libre. Il peut se reconnecter à tout moment.",
		"errpage.title":       "La connexion n'a pas abouti",
		"errpage.social":      "Nous n'avons pas pu finaliser votre connexion avec ce compte. Veuillez réessayer ou choisir un autre moyen de connexion.",
		"errpage.back":        "Retour à la connexion",
	},
	"it": {
		"brand.fallback":      "Wi-Fi ospiti",
		"info.button":         "Informazioni sul dispositivo",
		"info.none":           "Non rilevato",
		"notice.ended.data":   "Il tuo pacchetto Internet è terminato perché il traffico dati disponibile è stato esaurito.",
		"notice.ended.time":   "Il tuo pacchetto Internet è terminato perché il tempo di accesso è scaduto.",
		"err.room.credential": "Il numero di camera o il dato dell'ospite inserito non è corretto. Controlla il numero di camera e inserisci il nome completo, il cognome o il numero di prenotazione.",
		"err.room.technical":  "Al momento non riusciamo a verificare il tuo soggiorno. Riprova o contatta la reception.",
		"err.wait":            "Troppi tentativi. Attendi e riprova.",
		"err.wait.seconds":    "Troppi tentativi. Attendi {n} secondi e riprova.",
		"err.attempts":        "Troppi tentativi. Attendi un minuto e riprova.",
		"err.voucher.empty":   "Inserisci un codice voucher.",
		"err.voucher.invalid": "Questo codice voucher non ha funzionato. Controllalo e riprova.",
		"err.voucher.devices": "Questo voucher ha raggiunto il numero massimo di dispositivi. Disconnetti un altro dispositivo e riprova.",
		"err.account.empty":   "Inserisci nome utente e password.",
		"err.account.invalid": "Nome utente o password non corretti.",
		"err.account.devices": "Questo account ha raggiunto il numero massimo di dispositivi. Disconnetti un altro dispositivo e riprova.",
		"err.capacity":        "La rete ospiti è al completo. Riprova tra poco.",
		"err.device.network":  "Il tuo dispositivo non è connesso alla rete ospiti.",
		"err.device.detect":   "Impossibile rilevare l'indirizzo del tuo dispositivo.",
		"err.service":         "Qualcosa è andato storto. Riprova.",
		"err.packages.off":    "I pacchetti Internet non sono disponibili al momento. Rivolgiti alla reception.",
		"err.packages.none":   "Al momento non ci sono pacchetti Internet disponibili per te.",
		"err.package.gone":    "Questo pacchetto non è disponibile. Scegline un altro.",
		"err.signin.again":    "Accedi di nuovo.",
		"err.connect":         "Non siamo riusciti a connettere il tuo dispositivo. Riprova tra un momento.",
		"err.otp.send":        "Al momento non riusciamo a inviare il codice. Riprova o scegli un altro modo per accedere.",
		"err.otp.dest":        "Controlla i dati inseriti e riprova.",
		"err.otp.wait":        "Attendi un momento prima di richiedere un nuovo codice.",
		"err.otp.code":        "Il codice non è corretto. Controllalo e riprova.",
		"err.otp.expired":     "Questo codice non può più essere usato. Richiedine uno nuovo.",
		"unit.mbps":           "{n} Mbit/s",
		"unit.h":              "{n} h",
		"unit.min":            "{n} min",
		"unit.d":              "{n} gg",
		"pkg.title":           "Scegli il tuo pacchetto",
		"pkg.subtitle":        "Hai effettuato l'accesso. Seleziona un pacchetto per andare online.",
		"pkg.default":         "Accesso a Internet",
		"online.title":        "Sei online",
		"online.lead":         "Il tuo dispositivo è connesso a Internet.",
		"online.remaining":    "Tempo rimanente",
		"online.unlimited":    "Nessun limite di tempo",
		"online.status":       "Stato della connessione",
		"online.disconnect":   "Disconnetti",
		"online.back":         "Indietro",
		"tl.left":             "Ti restano {t} di tempo Internet",
		"tl.note":             "Il tempo scorre solo mentre sei connesso.",
		"tl.ends":             "Il tuo accesso termina il {date}, che il tempo venga usato o meno.",
		"tl.none":             "Nessun tempo",
		"dev.title":           "I tuoi dispositivi",
		"dev.lead":            "Questi sono i dispositivi che usano il tuo accesso a Internet. Rimuoverne uno libera il suo posto per un altro dispositivo — il tuo accesso non cambia e il dispositivo rimosso può riconnettersi in qualsiasi momento.",
		"dev.name":            "Dispositivo {n}",
		"dev.online":          "Connesso ora",
		"dev.offline":         "Non connesso",
		"dev.lastused":        "Ultimo utilizzo: {t}",
		"dev.justnow":         "proprio ora",
		"dev.ago":             "{t} fa",
		"dev.remove":          "Rimuovi questo dispositivo",
		"dev.confirm":         "Rimuovere il dispositivo {n}? Perderà il suo posto e potrà riconnettersi in qualsiasi momento.",
		"dev.yes":             "Rimuovi",
		"dev.keep":            "Mantieni",
		"dev.inuse":           "È in uso in questo momento, quindi non può essere rimosso. Prima disconnettilo dal Wi-Fi.",
		"dev.cannot":          "Al momento questo dispositivo non può essere rimosso.",
		"dev.refused":         "Non ha funzionato. Riprova tra un momento.",
		"dev.removed":         "Il dispositivo è stato rimosso e il suo posto è libero. Può riconnettersi in qualsiasi momento.",
		"errpage.title":       "Accesso non riuscito",
		"errpage.social":      "Non siamo riusciti a completare l'accesso con questo account. Riprova o scegli un altro modo per accedere.",
		"errpage.back":        "Torna all'accesso",
	},
	"ru": {
		"brand.fallback":      "Гостевой Wi-Fi",
		"info.button":         "Сведения об устройстве",
		"info.none":           "Не определён",
		"notice.ended.data":   "Ваш интернет-пакет закончился: лимит трафика исчерпан.",
		"notice.ended.time":   "Ваш интернет-пакет закончился: время доступа истекло.",
		"err.room.credential": "Номер комнаты или данные гостя введены неверно. Проверьте номер комнаты и введите полное имя, фамилию или номер бронирования.",
		"err.room.technical":  "Сейчас мы не можем проверить ваше проживание. Попробуйте ещё раз или обратитесь на стойку регистрации.",
		"err.wait":            "Слишком много попыток. Подождите и попробуйте снова.",
		"err.wait.seconds":    "Слишком много попыток. Подождите {n} с и попробуйте снова.",
		"err.attempts":        "Слишком много попыток. Подождите минуту и попробуйте снова.",
		"err.voucher.empty":   "Введите код ваучера.",
		"err.voucher.invalid": "Этот код ваучера не подошёл. Проверьте код и попробуйте снова.",
		"err.voucher.devices": "Для этого ваучера достигнут предел устройств. Отключите другое устройство и попробуйте снова.",
		"err.account.empty":   "Введите имя пользователя и пароль.",
		"err.account.invalid": "Неверное имя пользователя или пароль.",
		"err.account.devices": "Для этого аккаунта достигнут предел устройств. Отключите другое устройство и попробуйте снова.",
		"err.capacity":        "Гостевая сеть сейчас перегружена. Попробуйте чуть позже.",
		"err.device.network":  "Ваше устройство не подключено к гостевой сети.",
		"err.device.detect":   "Не удалось определить адрес вашего устройства.",
		"err.service":         "Что-то пошло не так. Попробуйте ещё раз.",
		"err.packages.off":    "Интернет-пакеты сейчас недоступны. Обратитесь на стойку регистрации.",
		"err.packages.none":   "Сейчас для вас нет доступных интернет-пакетов.",
		"err.package.gone":    "Этот пакет недоступен. Выберите другой.",
		"err.signin.again":    "Пожалуйста, войдите снова.",
		"err.connect":         "Не удалось подключить ваше устройство к интернету. Попробуйте через минуту.",
		"err.otp.send":        "Сейчас не удалось отправить код. Попробуйте ещё раз или выберите другой способ входа.",
		"err.otp.dest":        "Проверьте введённые данные и попробуйте снова.",
		"err.otp.wait":        "Подождите немного, прежде чем запрашивать новый код.",
		"err.otp.code":        "Неверный код. Проверьте его и попробуйте снова.",
		"err.otp.expired":     "Этот код больше нельзя использовать. Запросите новый.",
		"unit.mbps":           "{n} Мбит/с",
		"unit.h":              "{n} ч",
		"unit.min":            "{n} мин",
		"unit.d":              "{n} дн.",
		"pkg.title":           "Выберите пакет",
		"pkg.subtitle":        "Вы вошли. Выберите пакет, чтобы выйти в интернет.",
		"pkg.default":         "Доступ в интернет",
		"online.title":        "Вы в сети",
		"online.lead":         "Ваше устройство подключено к интернету.",
		"online.remaining":    "Осталось времени",
		"online.unlimited":    "Без ограничения по времени",
		"online.status":       "Состояние",
		"online.disconnect":   "Отключиться",
		"online.back":         "Назад",
		"tl.left":             "Осталось интернет-времени: {t}",
		"tl.note":             "Время расходуется только пока вы подключены.",
		"tl.ends":             "Ваш доступ закончится {date}, независимо от того, использовано ли время.",
		"tl.none":             "Время закончилось",
		"dev.title":           "Ваши устройства",
		"dev.lead":            "Эти устройства используют ваш доступ в интернет. Удаление устройства освобождает место для другого — ваш доступ не меняется, а удалённое устройство может подключиться снова в любой момент.",
		"dev.name":            "Устройство {n}",
		"dev.online":          "Сейчас подключено",
		"dev.offline":         "Не подключено",
		"dev.lastused":        "Последнее использование: {t}",
		"dev.justnow":         "только что",
		"dev.ago":             "{t} назад",
		"dev.remove":          "Удалить это устройство",
		"dev.confirm":         "Удалить устройство {n}? Оно освободит место и сможет подключиться снова в любой момент.",
		"dev.yes":             "Удалить",
		"dev.keep":            "Оставить",
		"dev.inuse":           "Устройство сейчас используется, поэтому его нельзя удалить. Сначала отключите его от Wi-Fi.",
		"dev.cannot":          "Сейчас это устройство нельзя удалить.",
		"dev.refused":         "Не получилось. Попробуйте ещё раз через минуту.",
		"dev.removed":         "Устройство удалено, его место свободно. Оно может подключиться снова в любой момент.",
		"errpage.title":       "Не удалось войти",
		"errpage.social":      "Не удалось завершить вход с этим аккаунтом. Попробуйте ещё раз или выберите другой способ входа.",
		"errpage.back":        "Вернуться ко входу",
	},
}

// The page strings join the one dictionary at start-up. A key defined twice would silently shadow the
// sign-in wording, so that is refused loudly rather than resolved.
func init() {
	for code, words := range pageStrings {
		dst := builtinStrings[code]
		if dst == nil {
			dst = map[string]string{}
			builtinStrings[code] = dst
		}
		for k, v := range words {
			if _, dup := dst[k]; dup {
				panic("portald: translation key defined twice: " + code + "/" + k)
			}
			dst[k] = v
		}
	}
}
