package main

import (
	"encoding/json"
	"net/http"
)

// THE WORDS THE PORTAL SPEAKS, AS DATA.
//
// These used to live inside the landing template as a JavaScript object literal, which made them invisible to
// everything except the guest's browser. Hotel Admin therefore had no way to SHOW an operator what the portal
// actually says in Italian: it could only offer an empty field with the English text as a placeholder, so
// picking Italiano looked like it had done nothing. Duplicating the six dictionaries into the admin would
// have fixed the symptom and created two sources of truth for fifty-one strings in six languages.
//
// So they are Go data now. The template renders them, and /api/languages serves them, from this one map.
// There is no second copy to keep in step.

// portalLanguage is one language the portal ships complete wording for.
type portalLanguage struct {
	Code  string `json:"code"`
	Label string `json:"label"`         // the language's own name for itself
	RTL   bool   `json:"rtl,omitempty"` // Arabic reads right to left
}

// portalLanguages is the offered set, in the order the selector shows them.
var portalLanguages = []portalLanguage{
	{Code: "en", Label: "English"},
	{Code: "ar", Label: "العربية", RTL: true},
	{Code: "de", Label: "Deutsch"},
	{Code: "fr", Label: "Français"},
	{Code: "it", Label: "Italiano"},
	{Code: "ru", Label: "Русский"},
}

// builtinStrings is code -> key -> wording. Every language carries every key; a test asserts it.
var builtinStrings = map[string]map[string]string{
	"en": {
		"account.pass":           "Password",
		"account.personal":       "Use Personal Account",
		"account.user":           "Username",
		"alt.title":              "Or sign in with",
		"btn.login":              "Login",
		"btn.reconnect":          "Reconnect",
		"btn.sendcode":           "Send code",
		"btn.submit":             "Submit",
		"btn.verify":             "Verify",
		"email.dest":             "Email address",
		"err.generic":            "We could not verify your stay. Please check your details or contact reception.",
		"err.retry":              "You can try again now.",
		"info.device":            "Your device",
		"info.help":              "Reception may ask for these if you need help connecting.",
		"info.ip":                "IP address",
		"info.mac":               "MAC address",
		"lang.label":             "Language",
		"method.account":         "Personal account",
		"method.email":           "Email",
		"method.pms":             "Room",
		"method.poststay":        "Post-stay",
		"method.sms":             "Phone",
		"method.social":          "Social",
		"method.voucher":         "Voucher",
		"notice.nomethods":       "There is no way to sign in on this network yet. Please contact reception.",
		"notice.nopackages":      "Internet access is not available here at the moment. You can still sign in, but there is nothing to connect you to yet — please let reception know.",
		"otp.code":               "Verification code",
		"otp.retry.email":        "Try a different email",
		"otp.retry.sms":          "Use a different number",
		"otp.sent.email":         "We sent a 6-digit code to",
		"otp.sent.sms":           "We texted a 6-digit code to",
		"pms.choose":             "Choose your internet package",
		"pms.prompt.any":         "First name, last name, or reservation number",
		"pms.prompt.either":      "Last name OR reservation number",
		"pms.prompt.firstname":   "First name on the reservation",
		"pms.prompt.lastname":    "Last name on the reservation",
		"pms.prompt.reservation": "Reservation / confirmation number",
		"pms.room":               "Room Number",
		"pms.secondary":          "Password",
		"poststay.hint":          "The PIN you were given at checkout",
		"poststay.pin":           "Post-stay PIN",
		"sms.dest":               "Phone number",
		"sms.hint":               "Include the country code, for example +44 20 7946 0958",
		"social.apple":           "Continue with Apple",
		"social.facebook":        "Continue with Facebook",
		"social.google":          "Continue with Google",
		"social.microsoft":       "Continue with Microsoft",
		"social.note":            "You will be redirected to the provider, then back here.",
		"tab.account":            "Account Login",
		"tab.guest":              "Guest Login",
		"terms.link":             "Terms of use",
		"voucher.label":          "Voucher Code",
	},
	"ar": {
		"account.pass":           "كلمة المرور",
		"account.personal":       "استخدام حساب شخصي",
		"account.user":           "اسم المستخدم",
		"alt.title":              "أو سجّل الدخول عبر",
		"btn.login":              "تسجيل الدخول",
		"btn.reconnect":          "إعادة الاتصال",
		"btn.sendcode":           "إرسال الرمز",
		"btn.submit":             "إرسال",
		"btn.verify":             "تحقق",
		"email.dest":             "البريد الإلكتروني",
		"err.generic":            "تعذّر التحقق من إقامتك. يرجى مراجعة بياناتك أو التواصل مع مكتب الاستقبال.",
		"err.retry":              "يمكنك المحاولة مرة أخرى الآن.",
		"info.device":            "جهازك",
		"info.help":              "قد يطلب منك مكتب الاستقبال هذه البيانات إذا احتجت مساعدة في الاتصال.",
		"info.ip":                "عنوان IP",
		"info.mac":               "عنوان MAC",
		"lang.label":             "اللغة",
		"method.account":         "حساب شخصي",
		"method.email":           "البريد الإلكتروني",
		"method.pms":             "الغرفة",
		"method.poststay":        "ما بعد المغادرة",
		"method.sms":             "الهاتف",
		"method.social":          "حسابات التواصل",
		"method.voucher":         "قسيمة",
		"notice.nomethods":       "لا توجد طريقة لتسجيل الدخول على هذه الشبكة بعد. يرجى التواصل مع مكتب الاستقبال.",
		"notice.nopackages":      "خدمة الإنترنت غير متاحة هنا في الوقت الحالي. يمكنك تسجيل الدخول، لكن لا توجد باقة لتوصيلك بها بعد — يرجى إبلاغ مكتب الاستقبال.",
		"otp.code":               "رمز التحقق",
		"otp.retry.email":        "جرّب بريداً إلكترونياً آخر",
		"otp.retry.sms":          "استخدم رقماً آخر",
		"otp.sent.email":         "أرسلنا رمزاً من ٦ أرقام إلى",
		"otp.sent.sms":           "أرسلنا رمزاً من ٦ أرقام برسالة نصية إلى",
		"pms.choose":             "اختر باقة الإنترنت",
		"pms.prompt.any":         "الاسم الأول أو اسم العائلة أو رقم الحجز",
		"pms.prompt.either":      "اسم العائلة أو رقم الحجز",
		"pms.prompt.firstname":   "الاسم الأول كما في الحجز",
		"pms.prompt.lastname":    "اسم العائلة كما في الحجز",
		"pms.prompt.reservation": "رقم الحجز أو التأكيد",
		"pms.room":               "رقم الغرفة",
		"pms.secondary":          "كلمة المرور",
		"poststay.hint":          "الرمز الذي تسلمته عند المغادرة",
		"poststay.pin":           "رمز ما بعد المغادرة",
		"sms.dest":               "رقم الهاتف",
		"sms.hint":               "أدرج رمز الدولة، مثل ⁦+44 20 7946 0958⁩", // the number isolated left-to-right, or it reads backwards
		"social.apple":           "المتابعة باستخدام Apple",
		"social.facebook":        "المتابعة باستخدام Facebook",
		"social.google":          "المتابعة باستخدام Google",
		"social.microsoft":       "المتابعة باستخدام Microsoft",
		"social.note":            "سيتم تحويلك إلى مزوّد الخدمة ثم تعود إلى هنا.",
		"tab.account":            "الدخول بحساب",
		"tab.guest":              "تسجيل دخول النزلاء",
		"terms.link":             "شروط الاستخدام",
		"voucher.label":          "رمز القسيمة",
	},
	"de": {
		"account.pass":           "Passwort",
		"account.personal":       "Persönliches Konto verwenden",
		"account.user":           "Benutzername",
		"alt.title":              "Oder anmelden mit",
		"btn.login":              "Anmelden",
		"btn.reconnect":          "Erneut verbinden",
		"btn.sendcode":           "Code senden",
		"btn.submit":             "Senden",
		"btn.verify":             "Bestätigen",
		"email.dest":             "E-Mail-Adresse",
		"err.generic":            "Wir konnten Ihren Aufenthalt nicht bestätigen. Bitte prüfen Sie Ihre Angaben oder wenden Sie sich an die Rezeption.",
		"err.retry":              "Sie können es jetzt erneut versuchen.",
		"info.device":            "Ihr Gerät",
		"info.help":              "Die Rezeption fragt möglicherweise nach diesen Angaben, wenn Sie Hilfe beim Verbinden brauchen.",
		"info.ip":                "IP-Adresse",
		"info.mac":               "MAC-Adresse",
		"lang.label":             "Sprache",
		"method.account":         "Persönliches Konto",
		"method.email":           "E-Mail",
		"method.pms":             "Zimmer",
		"method.poststay":        "Nach dem Aufenthalt",
		"method.sms":             "Telefon",
		"method.social":          "Social Media",
		"method.voucher":         "Gutschein",
		"notice.nomethods":       "In diesem Netzwerk gibt es noch keine Anmeldemöglichkeit. Bitte wenden Sie sich an die Rezeption.",
		"notice.nopackages":      "Internetzugang ist hier derzeit nicht verfügbar. Sie können sich anmelden, aber es gibt noch nichts, womit wir Sie verbinden können — bitte informieren Sie die Rezeption.",
		"otp.code":               "Bestätigungscode",
		"otp.retry.email":        "Andere E-Mail-Adresse verwenden",
		"otp.retry.sms":          "Andere Nummer verwenden",
		"otp.sent.email":         "Wir haben einen 6-stelligen Code gesendet an",
		"otp.sent.sms":           "Wir haben einen 6-stelligen Code per SMS gesendet an",
		"pms.choose":             "Wählen Sie Ihr Internetpaket",
		"pms.prompt.any":         "Vorname, Nachname oder Reservierungsnummer",
		"pms.prompt.either":      "Nachname ODER Reservierungsnummer",
		"pms.prompt.firstname":   "Vorname auf der Reservierung",
		"pms.prompt.lastname":    "Nachname auf der Reservierung",
		"pms.prompt.reservation": "Reservierungs- oder Bestätigungsnummer",
		"pms.room":               "Zimmernummer",
		"pms.secondary":          "Passwort",
		"poststay.hint":          "Die PIN, die Sie beim Check-out erhalten haben",
		"poststay.pin":           "PIN nach dem Aufenthalt",
		"sms.dest":               "Telefonnummer",
		"sms.hint":               "Bitte mit Ländervorwahl, zum Beispiel +44 20 7946 0958",
		"social.apple":           "Weiter mit Apple",
		"social.facebook":        "Weiter mit Facebook",
		"social.google":          "Weiter mit Google",
		"social.microsoft":       "Weiter mit Microsoft",
		"social.note":            "Sie werden zum Anbieter weitergeleitet und danach hierher zurückgebracht.",
		"tab.account":            "Konto-Anmeldung",
		"tab.guest":              "Gäste-Anmeldung",
		"terms.link":             "Nutzungsbedingungen",
		"voucher.label":          "Gutscheincode",
	},
	"fr": {
		"account.pass":           "Mot de passe",
		"account.personal":       "Utiliser un compte personnel",
		"account.user":           "Nom d'utilisateur",
		"alt.title":              "Ou connectez-vous avec",
		"btn.login":              "Se connecter",
		"btn.reconnect":          "Se reconnecter",
		"btn.sendcode":           "Envoyer le code",
		"btn.submit":             "Envoyer",
		"btn.verify":             "Vérifier",
		"email.dest":             "Adresse e-mail",
		"err.generic":            "Nous n'avons pas pu vérifier votre séjour. Veuillez vérifier vos informations ou contacter la réception.",
		"err.retry":              "Vous pouvez réessayer maintenant.",
		"info.device":            "Votre appareil",
		"info.help":              "La réception peut vous demander ces informations si vous avez besoin d'aide pour vous connecter.",
		"info.ip":                "Adresse IP",
		"info.mac":               "Adresse MAC",
		"lang.label":             "Langue",
		"method.account":         "Compte personnel",
		"method.email":           "E-mail",
		"method.pms":             "Chambre",
		"method.poststay":        "Après le séjour",
		"method.sms":             "Téléphone",
		"method.social":          "Réseaux sociaux",
		"method.voucher":         "Bon d'accès",
		"notice.nomethods":       "Aucun moyen de connexion n'est encore disponible sur ce réseau. Veuillez contacter la réception.",
		"notice.nopackages":      "L'accès à Internet n'est pas disponible ici pour le moment. Vous pouvez vous connecter, mais il n'y a encore rien à quoi vous relier — merci de prévenir la réception.",
		"otp.code":               "Code de vérification",
		"otp.retry.email":        "Essayer une autre adresse e-mail",
		"otp.retry.sms":          "Utiliser un autre numéro",
		"otp.sent.email":         "Nous avons envoyé un code à 6 chiffres à",
		"otp.sent.sms":           "Nous avons envoyé un code à 6 chiffres par SMS au",
		"pms.choose":             "Choisissez votre forfait Internet",
		"pms.prompt.any":         "Prénom, nom ou numéro de réservation",
		"pms.prompt.either":      "Nom de famille OU numéro de réservation",
		"pms.prompt.firstname":   "Prénom figurant sur la réservation",
		"pms.prompt.lastname":    "Nom de famille figurant sur la réservation",
		"pms.prompt.reservation": "Numéro de réservation ou de confirmation",
		"pms.room":               "Numéro de chambre",
		"pms.secondary":          "Mot de passe",
		"poststay.hint":          "Le code qui vous a été remis au départ",
		"poststay.pin":           "Code après séjour",
		"sms.dest":               "Numéro de téléphone",
		"sms.hint":               "Indiquez l'indicatif du pays, par exemple +44 20 7946 0958",
		"social.apple":           "Continuer avec Apple",
		"social.facebook":        "Continuer avec Facebook",
		"social.google":          "Continuer avec Google",
		"social.microsoft":       "Continuer avec Microsoft",
		"social.note":            "Vous serez redirigé vers le fournisseur, puis ramené ici.",
		"tab.account":            "Connexion au compte",
		"tab.guest":              "Connexion client",
		"terms.link":             "Conditions d'utilisation",
		"voucher.label":          "Code d'accès",
	},
	"it": {
		"account.pass":           "Password",
		"account.personal":       "Usa un account personale",
		"account.user":           "Nome utente",
		"alt.title":              "Oppure accedi con",
		"btn.login":              "Accedi",
		"btn.reconnect":          "Riconnetti",
		"btn.sendcode":           "Invia il codice",
		"btn.submit":             "Invia",
		"btn.verify":             "Verifica",
		"email.dest":             "Indirizzo e-mail",
		"err.generic":            "Non è stato possibile verificare il tuo soggiorno. Controlla i dati inseriti o contatta la reception.",
		"err.retry":              "Puoi riprovare adesso.",
		"info.device":            "Il tuo dispositivo",
		"info.help":              "La reception potrebbe chiederti questi dati se hai bisogno di aiuto per connetterti.",
		"info.ip":                "Indirizzo IP",
		"info.mac":               "Indirizzo MAC",
		"lang.label":             "Lingua",
		"method.account":         "Account personale",
		"method.email":           "E-mail",
		"method.pms":             "Camera",
		"method.poststay":        "Dopo il soggiorno",
		"method.sms":             "Telefono",
		"method.social":          "Social",
		"method.voucher":         "Voucher",
		"notice.nomethods":       "Su questa rete non è ancora disponibile alcun modo per accedere. Contatta la reception.",
		"notice.nopackages":      "Al momento l'accesso a Internet non è disponibile qui. Puoi comunque accedere, ma non c'è ancora nulla a cui collegarti — avvisa la reception.",
		"otp.code":               "Codice di verifica",
		"otp.retry.email":        "Usa un altro indirizzo e-mail",
		"otp.retry.sms":          "Usa un altro numero",
		"otp.sent.email":         "Abbiamo inviato un codice di 6 cifre a",
		"otp.sent.sms":           "Abbiamo inviato via SMS un codice di 6 cifre a",
		"pms.choose":             "Scegli il tuo pacchetto Internet",
		"pms.prompt.any":         "Nome, cognome o numero di prenotazione",
		"pms.prompt.either":      "Cognome OPPURE numero di prenotazione",
		"pms.prompt.firstname":   "Nome indicato nella prenotazione",
		"pms.prompt.lastname":    "Cognome indicato nella prenotazione",
		"pms.prompt.reservation": "Numero di prenotazione o di conferma",
		"pms.room":               "Numero di camera",
		"pms.secondary":          "Password",
		"poststay.hint":          "Il PIN che hai ricevuto al check-out",
		"poststay.pin":           "PIN dopo il soggiorno",
		"sms.dest":               "Numero di telefono",
		"sms.hint":               "Includi il prefisso internazionale, ad esempio +44 20 7946 0958",
		"social.apple":           "Continua con Apple",
		"social.facebook":        "Continua con Facebook",
		"social.google":          "Continua con Google",
		"social.microsoft":       "Continua con Microsoft",
		"social.note":            "Verrai reindirizzato al provider e poi di nuovo qui.",
		"tab.account":            "Accesso account",
		"tab.guest":              "Accesso ospiti",
		"terms.link":             "Condizioni d'uso",
		"voucher.label":          "Codice voucher",
	},
	"ru": {
		"account.pass":           "Пароль",
		"account.personal":       "Использовать личный аккаунт",
		"account.user":           "Имя пользователя",
		"alt.title":              "Или войдите через",
		"btn.login":              "Войти",
		"btn.reconnect":          "Подключиться снова",
		"btn.sendcode":           "Отправить код",
		"btn.submit":             "Отправить",
		"btn.verify":             "Подтвердить",
		"email.dest":             "Адрес эл. почты",
		"err.generic":            "Не удалось подтвердить ваше проживание. Проверьте данные или обратитесь на стойку регистрации.",
		"err.retry":              "Теперь можно попробовать снова.",
		"info.device":            "Ваше устройство",
		"info.help":              "На стойке регистрации могут попросить эти данные, если вам нужна помощь с подключением.",
		"info.ip":                "IP-адрес",
		"info.mac":               "MAC-адрес",
		"lang.label":             "Язык",
		"method.account":         "Личный аккаунт",
		"method.email":           "Эл. почта",
		"method.pms":             "Номер",
		"method.poststay":        "После выезда",
		"method.sms":             "Телефон",
		"method.social":          "Соцсети",
		"method.voucher":         "Ваучер",
		"notice.nomethods":       "В этой сети пока нет способа войти. Пожалуйста, обратитесь на стойку регистрации.",
		"notice.nopackages":      "Доступ в интернет здесь сейчас недоступен. Вы можете войти, но подключать пока не к чему — сообщите об этом на стойку регистрации.",
		"otp.code":               "Код подтверждения",
		"otp.retry.email":        "Указать другой адрес",
		"otp.retry.sms":          "Указать другой номер",
		"otp.sent.email":         "Мы отправили 6-значный код на",
		"otp.sent.sms":           "Мы отправили 6-значный код в SMS на номер",
		"pms.choose":             "Выберите интернет-пакет",
		"pms.prompt.any":         "Имя, фамилия или номер брони",
		"pms.prompt.either":      "Фамилия ИЛИ номер брони",
		"pms.prompt.firstname":   "Имя, указанное в брони",
		"pms.prompt.lastname":    "Фамилия, указанная в брони",
		"pms.prompt.reservation": "Номер брони или подтверждения",
		"pms.room":               "Номер комнаты",
		"pms.secondary":          "Пароль",
		"poststay.hint":          "PIN, который вам выдали при выезде",
		"poststay.pin":           "PIN после выезда",
		"sms.dest":               "Номер телефона",
		"sms.hint":               "Укажите код страны, например +44 20 7946 0958",
		"social.apple":           "Продолжить с Apple",
		"social.facebook":        "Продолжить с Facebook",
		"social.google":          "Продолжить с Google",
		"social.microsoft":       "Продолжить с Microsoft",
		"social.note":            "Вы перейдёте на сайт провайдера, а затем вернётесь сюда.",
		"tab.account":            "Вход в аккаунт",
		"tab.guest":              "Вход для гостей",
		"terms.link":             "Условия использования",
		"voucher.label":          "Код ваучера",
	},
}

// languages serves the shipped wording.
//
// One source, two consumers: the landing page renders this map, and Hotel Admin fetches it (through edged)
// to show an operator the actual Italian a guest will read. The alternative -- a copy of six dictionaries in
// the admin -- is 306 strings maintained twice, and the drift would show up as an operator confidently
// editing wording nobody sees.
func (h *handler) languages(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Cache-Control", "public, max-age=300")
	_ = json.NewEncoder(w).Encode(map[string]any{
		"languages": portalLanguages,
		"strings":   builtinStrings,
	})
}
