package payment

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// FINANCIAL_RECOVERY_MODE — the runtime half.
//
// The database holds the rules (see migration 0019). This file is the small amount of behaviour that has to
// live in the process: reconciling the epoch at startup, reading recovery state, and giving an operator
// surface something to call.
//
// The ordering rule that matters: ReconcileEpoch runs BEFORE any financial worker starts. A worker that
// begins draining an outbox and only then discovers it is running on restored data has already sent
// whatever it sent.

// RecoveryStatus is what a site's financial history currently looks like.
type RecoveryStatus struct {
	Epoch      int64
	Reason     string
	Active     bool
	HeldTotal  int
	HeldOpen   int
	EnteredAt  string
	ReleasedAt string
}

// Hold is one piece of financial work whose fate the restored database cannot vouch for.
type Hold struct {
	ID          string
	Kind        string
	WorkID      string
	HeldStatus  string
	AmountMinor *int64
	Currency    string
	Resolution  string
	HeldAt      string
}

// SystemIdentity reads the running database's own identity marker.
//
// It comes from pg_control rather than from anything StayConnect writes, and that is the point: a value the
// application stores would be restored along with everything else, and would therefore agree with itself
// after exactly the event it is supposed to detect. The control file's identifier is generated by initdb
// and by the restore, so a restored copy reports a different one.
func SystemIdentity(ctx context.Context, pool *pgxpool.Pool) (string, error) {
	var id string
	err := pool.QueryRow(ctx, `SELECT system_identifier::text FROM pg_control_system()`).Scan(&id)
	if err != nil {
		return "", fail(ErrRepo, "could not read the database system identity")
	}
	return id, nil
}

// ReconcileEpoch is called at startup, per site, BEFORE any financial worker runs.
//
// It is idempotent: an ordinary restart finds the stored identity unchanged and returns UNCHANGED without
// writing anything. It returns one of INITIALIZED, UNCHANGED, RECOVERY_ENTERED or RECOVERY_ACTIVE.
func (e *Engine) ReconcileEpoch(ctx context.Context, tenantID, siteID string) (string, error) {
	ident, err := SystemIdentity(ctx, e.pool)
	if err != nil {
		return "", err
	}
	var out string
	if err := e.pool.QueryRow(ctx,
		`SELECT iam_v2.p4_reconcile_financial_epoch($1,$2,$3)`, tenantID, siteID, ident).Scan(&out); err != nil {
		return "", classify(err)
	}
	return out, nil
}

// RecoveryActive reports whether money movement is currently held for a site.
func (e *Engine) RecoveryActive(ctx context.Context, tenantID, siteID string) (bool, error) {
	var b bool
	if err := e.pool.QueryRow(ctx,
		`SELECT iam_v2.p4_financial_recovery_active($1,$2)`, tenantID, siteID).Scan(&b); err != nil {
		return false, classify(err)
	}
	return b, nil
}

// RecoveryStatusFor reads the open epoch, or the latest one if none is open.
func (e *Engine) RecoveryStatusFor(ctx context.Context, tenantID, siteID string) (RecoveryStatus, error) {
	var s RecoveryStatus
	var released *string
	err := e.pool.QueryRow(ctx, `
SELECT epoch, reason, recovery_active, held_total::int, held_open::int,
       entered_at::text, released_at::text
  FROM iam_v2.v_financial_recovery
 WHERE tenant_id=$1 AND site_id=$2
 ORDER BY (released_at IS NULL) DESC, epoch DESC LIMIT 1`, tenantID, siteID).
		Scan(&s.Epoch, &s.Reason, &s.Active, &s.HeldTotal, &s.HeldOpen, &s.EnteredAt, &released)
	if errors.Is(err, pgx.ErrNoRows) {
		return RecoveryStatus{}, nil
	}
	if err != nil {
		return RecoveryStatus{}, classify(err)
	}
	if released != nil {
		s.ReleasedAt = *released
	}
	return s, nil
}

// OpenHolds lists work awaiting an operator's conclusion. Bounded by construction: the caller cannot ask
// for an unbounded page, because an operator surface that can be made to return the whole financial history
// is a denial-of-service and a data-exposure problem at the same time.
func (e *Engine) OpenHolds(ctx context.Context, tenantID, siteID string, limit int) ([]Hold, error) {
	if limit <= 0 || limit > 200 {
		limit = 100
	}
	rows, err := e.pool.Query(ctx, `
SELECT id::text, work_kind, work_id::text, held_status, amount_minor, coalesce(currency,''),
       coalesce(resolution,''), held_at::text
  FROM iam_v2.financial_recovery_holds
 WHERE tenant_id=$1 AND site_id=$2 AND resolution IS NULL
 ORDER BY held_at, id LIMIT $3`, tenantID, siteID, limit)
	if err != nil {
		return nil, classify(err)
	}
	defer rows.Close()
	var out []Hold
	for rows.Next() {
		var h Hold
		if err := rows.Scan(&h.ID, &h.Kind, &h.WorkID, &h.HeldStatus, &h.AmountMinor, &h.Currency,
			&h.Resolution, &h.HeldAt); err != nil {
			return nil, classify(err)
		}
		out = append(out, h)
	}
	return out, rows.Err()
}

// ResolveHold records an operator's conclusion about one held item. It moves no money and replays nothing.
func (e *Engine) ResolveHold(ctx context.Context, holdID, resolution, actorID, note string) error {
	_, err := e.pool.Exec(ctx,
		`SELECT iam_v2.p4_resolve_recovery_hold($1::uuid,$2::text,$3::uuid,$4::text)`,
		holdID, resolution, actorID, note)
	return classify(err)
}

// ReleaseRecovery ends recovery for a site. The database refuses while any hold is unresolved; there is no
// force parameter here because there is no force path there.
func (e *Engine) ReleaseRecovery(ctx context.Context, tenantID, siteID, actorID, note string) (int64, error) {
	var epoch int64
	if err := e.pool.QueryRow(ctx,
		`SELECT iam_v2.p4_release_financial_recovery($1::uuid,$2::uuid,$3::uuid,$4::text)`,
		tenantID, siteID, actorID, note).Scan(&epoch); err != nil {
		return 0, classify(err)
	}
	return epoch, nil
}

// DeclareRecovery holds money movement without a restore, for an operator who has reason to doubt the
// financial record. Entering is always available; leaving is what is controlled.
func (e *Engine) DeclareRecovery(ctx context.Context, tenantID, siteID, actorID, reason string) (int64, error) {
	var epoch int64
	if err := e.pool.QueryRow(ctx,
		`SELECT iam_v2.p4_declare_financial_recovery($1::uuid,$2::uuid,$3::uuid,$4::text)`,
		tenantID, siteID, actorID, reason).Scan(&epoch); err != nil {
		return 0, classify(err)
	}
	return epoch, nil
}
