#!/usr/bin/env python3
"""A GRANT ONLY A MIGRATION MAKES IS A GRANT THAT DISAPPEARS.

WHY THIS EXISTS, AND IT IS NOT A STYLE RULE.

deploy/gatep/gatep-grants.sql opens by taking everything away:

    REVOKE ALL PRIVILEGES ON ALL TABLES    IN SCHEMA public  FROM <each service role>
    REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public  FROM <each service role>
    REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public  FROM <each service role>
    ... and the same four for iam_v2 ...

and then re-grants exactly what the per-service Gate-P files name. Gate-P runs AFTER the numbered migrations
-- in scripts/clean-install-reconstruction.sh and in a real install -- so a privilege that exists ONLY in a
migration is revoked moments after it was granted.

FOUR REAL CASES. Migrations 0080, 0081, 0082 and 0083 each added one operator read a Hotel-Admin screen
needs. None was mirrored in Gate-P. The generated factory-clean baseline -- a dump of the end state of the
whole install chain -- contained ZERO of the four, while the PRE-LIVE appliance had all four, because there
they were applied by hand after Gate-P last ran. So the appliance worked and a rebuilt appliance would not,
and the screens that would silently break were exactly the ones those migrations were written to fix: the
Audit log (which had already once reported "No audit entries" while 379 rows existed), the Usage Explorer,
Policy History and Guest Activity.

WHY NO EXISTING CHECK CAUGHT IT. scripts/factory-clean-baseline-verify.sh compares the baseline path against
the upgrade path, and its catalog DOES include TABLEGRANT rows -- but both paths end with the same revoke, so
both were equally wrong and the comparison was IDENTICAL. A defect that is symmetric is invisible to a
symmetry check. This check is asymmetric on purpose: it compares migrations against Gate-P, not a path
against a path.

THE RULE. Every grant a numbered migration makes to a service role (svc_*) must also be named in
deploy/gatep/. The migration is still the right place to record WHY -- that is where the reasoning lives --
but Gate-P is what survives a reconcile. The Room-Login privilege chain already followed this rule and says
so: a privilege is "fixed at its authoritative source -- migrations 0057 and 0058 plus the per-service
Gate-P files, so a reconcile keeps them".

WHAT IT CHECKS, deliberately narrowly:

  * GRANT statements in data-plane/migrations/*.up.sql whose grantee is a svc_* role.
  * Matching is on (privilege-kind, object) -- a TABLE grant on iam_v2.devices must find a TABLE grant on
    iam_v2.devices to the same role somewhere in deploy/gatep/. Column lists are compared as a set when
    both sides carry one.
  * EXECUTE grants on functions are matched by function NAME, not full signature: Gate-P writes the full
    argument list and migrations often do not, and a name match is the honest strength of this check.

WHAT IT DOES NOT CHECK. Whether the grant is correct, whether it is too broad, or whether Gate-P grants
things no migration asked for (that is normal -- Gate-P is the authority). Only durability.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MIGRATIONS = os.path.join(ROOT, "data-plane", "migrations")
GATEP = os.path.join(ROOT, "deploy", "gatep")

# THE FINAL SCHEMA, AS THE INSTALL CHAIN ACTUALLY ENDS UP. Used to tell a DURABILITY gap apart from a DEAD
# grant.
#
# A migration may grant on an object that a LATER migration drops, and that grant is not a gap -- there is
# nothing left to protect. Two of the forty this check first reported were exactly that: 0069 created
# iam_v2.stay_event_reoffers and iam_v2.pms_reoffer_stay_event and granted on both, and 0070 dropped both
# (refusing first if the audit log held rows). Demanding a Gate-P entry for them would have meant granting
# on objects that do not exist, which fails the install.
#
# The baseline is the right authority because it is a dump of the END STATE of the whole chain, it is
# regenerated by any delivery that changes a migration, and scripts/factory-clean-baseline-verify.sh proves
# it agrees with the upgrade path object for object. So "absent from the baseline" means "absent at the end",
# checked from the tree with no database.
BASELINE = os.path.join(ROOT, "data-plane", "migrations", "baseline", "0000_production_baseline.sql")

# GRANT <privs> ON [TABLE|FUNCTION|SCHEMA|SEQUENCE] <object> TO <role>[, <role>]
GRANT_RE = re.compile(
    r"\bGRANT\s+(?P<privs>.+?)\s+ON\s+(?P<kind>TABLE\s+|FUNCTION\s+|SCHEMA\s+|SEQUENCE\s+|ALL\s+TABLES\s+IN\s+SCHEMA\s+)?"
    r"(?P<object>[A-Za-z0-9_.\"]+(?:\s*\([^)]*\))?)\s+TO\s+(?P<roles>[A-Za-z0-9_, \"]+)",
    re.I | re.S)

# REVOKE <privs> ON [TABLE|FUNCTION|...] <object> FROM <role>[, <role>]
#
# THIS CHECK WAS BLIND TO REVOKES, AND THE BLINDNESS WAS NOT ACADEMIC.
#
# It compared the GRANT statements in migrations against the GRANT statements in deploy/gatep/ and reported
# anything missing from the second as a durability gap. A privilege that a migration grants and a LATER
# migration deliberately takes away therefore looked exactly like a gap -- so mirroring "every grant a
# migration makes" into Gate-P re-granted it, on every factory-clean install and every reconcile, and
# Gate-P runs AFTER the migrations so nothing downstream could undo it.
#
# That is how increment 2 restored svc_scd's EXECUTE on iam_v2.p6_guest_release_device(uuid,uuid,int) --
# the three-argument release primitive whose whole purpose is to be owner-only, because a caller that can
# pass its own p_max_releases_per_hour can pass 2147483647 and walk through the approved throttle using the
# approved function. 0033 granted it; 0034 revoked it and ASSERTS in the same file that svc_scd no longer
# holds it. The assertion runs at migration time, before Gate-P, so it could not catch the reversal either.
#
# A check that compares only the statements it already knows about is a check that reports the shape of its
# own parser. Revokes are now modelled, in file order, as the second half of the same timeline.
REVOKE_RE = re.compile(
    r"\bREVOKE\s+(?P<privs>.+?)\s+ON\s+(?P<kind>TABLE\s+|FUNCTION\s+|SCHEMA\s+|SEQUENCE\s+|ALL\s+TABLES\s+IN\s+SCHEMA\s+)?"
    r"(?P<object>[A-Za-z0-9_.\"]+(?:\s*\([^)]*\))?)\s+FROM\s+(?P<roles>[A-Za-z0-9_, \"]+)",
    re.I | re.S)

SERVICE_ROLE_RE = re.compile(r"^svc_[a-z0-9_]+$", re.I)

# THE DEBT THIS LIST HELD IS PAID. IT IS EMPTY, AND THE MECHANISM STAYS.
#
# It held forty entries: service-role grants made by migrations that deploy/gatep/ never re-granted, so they
# did not survive a factory-clean install. All forty are resolved:
#
#   38 MIRRORED into the per-service Gate-P files, each verified against PRE-LIVE 172.21.60.25 before being
#      written -- 29 were present there and 9 were ABSENT WITH THEIR OBJECTS PRESENT, which means those nine
#      were broken on the live appliance and not merely on a rebuild. Verifying first is what made this a
#      reproduction of the appliance's real privilege state rather than a bulk guess.
#   2  DEAD: 0069 granted on iam_v2.pms_reoffer_stay_event and iam_v2.stay_event_reoffers and 0070 dropped
#      both. Granting on either would fail the install, so the check now reads the generated baseline and
#      reports them as dead rather than missing.
#
# THE LIST STAYS, EMPTY, ON PURPOSE. A future migration that grants to a svc_* role without mirroring it here
# fails immediately, and an entry added to this set has to carry its reason in the commit that adds it. An
# empty exception list is the strongest state this check can be in; deleting the mechanism would be the
# weakest.
PREDATING_THIS_CHECK = set()

_failures = []

# Grant and revoke statements in file order, per (role, kind, object). Filled by collect()/collect_revokes()
# for MIGRATIONS only -- deploy/gatep/ is a set of grants with no ordering question.
ORDERED = {}
ORDERED_REV = {}


def bad(msg, where=""):
    _failures.append(msg)
    print("  FAIL %s%s" % (msg, ("\n           " + where) if where else ""))


def ok(msg):
    print("  ok: %s" % msg)


def strip_sql_comments(text):
    """Remove -- line comments so a grant quoted in prose is not read as a grant."""
    out = []
    for line in text.splitlines():
        s = line.lstrip()
        if s.startswith("--"):
            continue
        # An inline trailing comment cannot contain a grant we care about; cut it.
        i = line.find("--")
        out.append(line[:i] if i >= 0 else line)
    return "\n".join(out)


def normalise_object(kind, obj):
    """Return (kind, name, columns) with the function signature reduced to a bare name."""
    obj = obj.strip().strip('"')
    cols = frozenset()
    m = re.match(r"^([A-Za-z0-9_.\"]+)\s*\((.*)\)$", obj, re.S)
    if m:
        name = m.group(1).strip().strip('"')
        inner = m.group(2)
        if (kind or "").strip().upper().startswith("FUNCTION"):
            # A signature, not a column list. Match by name: Gate-P spells the full argument list and
            # migrations often do not, and a name match is the honest strength of this check.
            return ("FUNCTION", name.lower(), frozenset())
        cols = frozenset(c.strip().strip('"').lower() for c in inner.split(",") if c.strip())
        return ("TABLE", name.lower(), cols)
    k = (kind or "").strip().upper()
    if k.startswith("FUNCTION"):
        return ("FUNCTION", obj.lower(), cols)
    if k.startswith("SCHEMA"):
        return ("SCHEMA", obj.lower(), cols)
    if k.startswith("SEQUENCE"):
        return ("SEQUENCE", obj.lower(), cols)
    if k.startswith("ALL"):
        return ("ALL_TABLES_IN_SCHEMA", obj.lower(), cols)
    return ("TABLE", obj.lower(), cols)


def collect(paths, record_order=False):
    """{(role, kind, object): [(privs, columns, source)]}

    record_order is for MIGRATIONS ONLY. It feeds the grant/revoke timeline, and feeding deploy/gatep/ into
    that timeline silently cancels every revoke: Gate-P's paths sort after the migrations', so its grants
    land last in the fold and every withdrawn privilege reads as still held. This check reported PASS with
    three reversed security boundaries sitting in the tree until that was separated -- the fix for a blind
    spot creating a new one in the same function.
    """
    found = {}
    for path in paths:
        try:
            with open(path, encoding="utf-8", errors="replace") as fh:
                text = strip_sql_comments(fh.read())
        except OSError:
            continue
        rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
        for m in GRANT_RE.finditer(text):
            privs = " ".join(m.group("privs").split()).upper()
            # A column list can sit in the PRIVS half: GRANT SELECT (a, b) ON t TO r
            pcols = frozenset()
            pm = re.match(r"^([A-Z, ]+?)\s*\((.*)\)$", privs, re.S)
            if pm:
                privs = " ".join(pm.group(1).split())
                pcols = frozenset(c.strip().lower() for c in pm.group(2).split(",") if c.strip())
            kind, obj, ocols = normalise_object(m.group("kind"), m.group("object"))
            cols = pcols or ocols
            for role in m.group("roles").split(","):
                role = role.strip().strip('"')
                if not SERVICE_ROLE_RE.match(role):
                    continue
                found.setdefault((role.lower(), kind, obj), []).append((privs, cols, rel))
                if record_order:
                    ORDERED.setdefault((role.lower(), kind, obj), []).append(((rel, m.start()), "+" + privs))
    return found


def collect_revokes(paths):
    """{(role, kind, object): [(privs, source)]} -- every service-role REVOKE, in file order.

    The privileges are kept because a REVOKE is not always total: 0034 revokes SELECT and INSERT on
    guest_device_actions and leaves nothing, but a migration could revoke one privilege of several.
    """
    found = {}
    for path in paths:
        try:
            with open(path, encoding="utf-8", errors="replace") as fh:
                text = strip_sql_comments(fh.read())
        except OSError:
            continue
        rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
        for m in REVOKE_RE.finditer(text):
            privs = " ".join(m.group("privs").split()).upper()
            kind, obj, _ = normalise_object(m.group("kind"), m.group("object"))
            for role in m.group("roles").split(","):
                role = role.strip().strip('"')
                if not SERVICE_ROLE_RE.match(role):
                    continue
                found.setdefault((role.lower(), kind, obj), []).append((privs, rel))
                ORDERED_REV.setdefault((role.lower(), kind, obj), []).append(((rel, m.start()), "-" + privs))
    return found


def priv_set(privs):
    """'SELECT, INSERT' -> {'SELECT','INSERT'}. ALL PRIVILEGES is a wildcard and is kept as one token."""
    text = privs.upper().replace("PRIVILEGES", "").strip()
    if text.startswith("ALL"):
        return {"ALL"}
    return {p.strip() for p in text.split(",") if p.strip()}


def withdrawn_privileges(grants, revokes):
    """Privileges a migration granted that a LATER migration took away, for one (role, kind, object).

    THE FOLD IS THE POINT, and a coarser check got this wrong in a way worth recording. The first version
    compared (role, kind, object) membership only, and reported svc_edged's SELECT on
    iam_v2.appliance_product_settings as a reversal -- 0034 revokes INSERT, UPDATE and DELETE there and
    leaves SELECT deliberately in place, which the operator screen needs. A check that cannot tell a partial
    revoke from a total one produces exactly the kind of confident false positive that gets a real finding
    dismissed along with it.
    """
    held = set()
    for order, privs in sorted(grants + revokes):
        if privs[0] == "+":
            held |= priv_set(privs[1:])
        else:
            held -= priv_set(privs[1:])
            if "ALL" in held:
                held.discard("ALL")
    ever = set()
    for _order, privs in grants:
        if privs[0] == "+":
            ever |= priv_set(privs[1:])
    return ever - held


def final_schema_objects():
    """Every schema-qualified table and function name the generated baseline creates, lowercased."""
    try:
        with open(BASELINE, encoding="utf-8", errors="replace") as fh:
            text = fh.read()
    except OSError:
        return None  # No baseline to consult: do not silently excuse anything.
    names = set()
    for m in re.finditer(
            r"^CREATE\s+(?:OR\s+REPLACE\s+)?(?:TABLE|VIEW|MATERIALIZED\s+VIEW|FUNCTION|PROCEDURE)\s+"
            r"([A-Za-z0-9_]+\.[A-Za-z0-9_]+)", text, re.I | re.M):
        names.add(m.group(1).lower())
    return names


def sql_files(directory, suffix):
    out = []
    if not os.path.isdir(directory):
        return out
    for fn in sorted(os.listdir(directory)):
        if fn.endswith(suffix):
            out.append(os.path.join(directory, fn))
    return out


def main():
    print("== migration grant durability (migrations vs deploy/gatep) ==")
    mig = collect(sql_files(MIGRATIONS, ".up.sql"), record_order=True)
    gate = collect(sql_files(GATEP, ".sql"))
    revoked = collect_revokes(sql_files(MIGRATIONS, ".up.sql"))

    if not mig:
        bad("no service-role GRANT was found in any migration; the check cannot be meaningful")
    if not gate:
        bad("no service-role GRANT was found in deploy/gatep; the check cannot be meaningful")

    final = final_schema_objects()
    if final is None:
        bad("the generated baseline could not be read, so a dead grant cannot be told apart from a "
            "durability gap; refusing to guess")
        final = set()
    elif not final:
        bad("the generated baseline names no objects, which cannot be right; refusing to excuse anything")

    # WITHDRAWN: privileges granted by one migration and revoked by a LATER one, from the same role, on the
    # same object. Folded in file order, exactly as the chain applies, and PER PRIVILEGE -- a partial revoke
    # leaves the rest standing and must not be reported as a reversal.
    withdrawn = {}
    for key in ORDERED_REV:
        if key not in ORDERED:
            continue
        gone = withdrawn_privileges(ORDERED[key], ORDERED_REV[key])
        if gone:
            granted_in = sorted({o[0] for o, _ in ORDERED[key]})[-1]
            revoked_in = sorted({o[0] for o, _ in ORDERED_REV[key]})[-1]
            withdrawn[key] = (sorted(gone), granted_in, revoked_in)

    checked = 0
    carried = []
    dead = []
    reversed_in_gatep = []
    withheld = []
    stale = set(PREDATING_THIS_CHECK)
    for key, entries in sorted(mig.items()):
        role, kind, obj = key
        checked += 1
        # A WITHDRAWN privilege must NOT be in Gate-P. This is the opposite failure from a durability gap
        # and strictly the more dangerous of the two: a gap removes a privilege something needs and the
        # feature visibly breaks, while this silently restores one that was taken away on purpose, on every
        # install, with nothing downstream to undo it.
        if key in withdrawn:
            gone, granted_in, revoked_in = withdrawn[key]
            gate_privs = set()
            for privs, _cols, _src in gate.get(key, []):
                gate_privs |= priv_set(privs)
            restored = sorted(gate_privs & set(gone))
            if restored:
                reversed_in_gatep.append((role, kind.lower(), obj, restored, granted_in, revoked_in))
            else:
                withheld.append((role, kind.lower(), obj, ", ".join(gone), revoked_in))
            # Whatever the migrations LEFT in place still has to survive Gate-P, so fall through to the
            # ordinary durability check when the revoke was partial.
            if set(gone) == {p for privs, _c, _s in mig[key] for p in priv_set(privs)}:
                continue
        if key in gate:
            continue
        # A grant on an object the chain does not end up with is DEAD, not missing.
        if kind in ("TABLE", "FUNCTION") and final and obj not in final:
            dead.append((role, kind.lower(), obj))
            stale.discard((role, kind.lower(), obj))
            continue
        # A schema-wide grant in Gate-P covers a table grant on that schema's tables.
        schema = obj.split(".")[0] if "." in obj else ""
        if kind == "TABLE" and schema and (role, "ALL_TABLES_IN_SCHEMA", schema) in gate:
            continue
        if (role, kind.lower(), obj) in PREDATING_THIS_CHECK:
            carried.append((role, kind.lower(), obj))
            stale.discard((role, kind.lower(), obj))
            continue
        sources = sorted({src for _, _, src in entries})
        privs = sorted({p for p, _, _ in entries})
        bad(
            "%s is granted %s on %s %s by a migration, and deploy/gatep/ never grants it -- "
            "gatep-grants.sql revokes all privileges from the service roles and runs AFTER the migrations, "
            "so this privilege does not survive a factory-clean install"
            % (role, "/".join(privs), kind.lower(), obj),
            "granted in: %s" % ", ".join(sources),
        )

    # AN EXCEPTION THAT NO LONGER APPLIES IS ITSELF A FAILURE. If a grant was mirrored into Gate-P, or the
    # migration that made it was changed, the list must shrink -- otherwise it decays into a blanket excuse.
    for role, kind, obj in sorted(stale):
        bad("(%s, %s, %s) is listed as predating this check but no migration grants it any more, or it is "
            "now mirrored in deploy/gatep/; remove it from PREDATING_THIS_CHECK" % (role, kind, obj))

    for role, kind, obj, restored, granted_in, revoked_in in sorted(reversed_in_gatep):
        bad(
            "deploy/gatep/ grants %s %s on %s %s, which %s DELIBERATELY REVOKED. Gate-P runs AFTER the "
            "migrations, so this restores a privilege that was taken away on purpose -- on every "
            "factory-clean install and every reconcile, with nothing downstream to undo it."
            % (role, "/".join(restored), kind, obj, revoked_in),
            "granted in: %s, then revoked in: %s" % (granted_in, revoked_in),
        )

    for role, kind, obj, gone, revoked_in in sorted(withheld):
        print("  ok: %s's %s %s on %s is WITHDRAWN by %s and is correctly absent from deploy/gatep/"
              % (role, gone, kind, obj, revoked_in))

    for role, kind, obj in sorted(dead):
        print("  ok: %s's %s grant on %s is DEAD -- a later migration drops the object, so there is nothing "
              "for Gate-P to keep" % (role, kind, obj))

    if not _failures:
        if carried:
            ok("%d of %d service-role grants made by migrations are named in deploy/gatep/; %d listed as "
               "predating this check" % (checked - len(carried), checked, len(carried)))
        else:
            ok("all %d service-role grants made by migrations are also named in deploy/gatep/, and the %d "
               "a later migration withdrew are correctly absent from it" % (checked, len(withheld)))

    print("=" * 50)
    if _failures:
        print("MIGRATION_GRANT_DURABILITY = FAIL (%d)" % len(_failures))
        return 1
    print("MIGRATION_GRANT_DURABILITY = PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
