"use client";

// GENERATED PASSWORD FORMAT — which characters, and how many, a GENERATED client-account password uses.
//
// A persisted, audited, per-site setting (migration 0104). Every bound on this screen comes from the appliance:
// the styles, each style's minimum length (a 40-bit entropy floor) and the maximum. Nothing here hardcodes a
// number the server enforces, so the browser can never offer a length the appliance would refuse.
//
// It changes only passwords GENERATED afterwards. Existing passwords and operator-typed passwords are untouched.

import * as React from "react";
import { History, Pencil, RefreshCw } from "lucide-react";
import {
  api,
  type AccountPasswordFormat,
  type AccountPasswordFormatChange,
  type AccountPasswordStyle,
} from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card, CardBody, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { DialogForm } from "@/components/ui/dialog";
import { Callout, ErrorBanner } from "@/components/ui/error-banner";
import { Field, Input, Select } from "@/components/ui/input";
import { KeyValueGrid, OptionCard, Timeline } from "@/components/ui/data";
import { Skeleton } from "@/components/ui/misc";
import { useToast } from "@/components/ui/toast";
import { formatRelative } from "@/lib/utils";

/** The same bound the server applies (validReason: 4-500 characters). */
export function formatReasonProblem(reason: string): string | null {
  const n = reason.trim().length;
  if (n < 4) return "Give a reason of at least 4 characters. It is recorded with your name.";
  if (n > 500) return "Keep the reason under 500 characters.";
  return null;
}

/** An illustration of the shape only, drawn in the browser. The real password is generated by the appliance. */
export function examplePassword(alphabet: string, length: number): string {
  if (!alphabet || length <= 0) return "";
  const out: string[] = [];
  const buf = new Uint32Array(length);
  const c = (globalThis as { crypto?: Crypto }).crypto;
  if (c?.getRandomValues) c.getRandomValues(buf);
  else for (let i = 0; i < length; i++) buf[i] = Math.floor(Math.random() * 2 ** 32);
  for (let i = 0; i < length; i++) out.push(alphabet[buf[i] % alphabet.length]);
  return out.join("");
}

function isFormat(v: unknown): v is AccountPasswordFormat {
  const f = v as AccountPasswordFormat | null;
  return !!f && typeof f.password_style === "string" && typeof f.password_length === "number" &&
    !!f.limits && Array.isArray(f.limits.styles) && f.limits.styles.length > 0;
}

function styleOf(f: AccountPasswordFormat, key: string): AccountPasswordStyle | undefined {
  return f.limits.styles.find((s) => s.key === key);
}

export function formatWords(f: AccountPasswordFormat, key: string, length: number): string {
  const s = styleOf(f, key);
  return `${length} characters, ${(s?.label ?? key).toLowerCase()}`;
}

export function PasswordFormatCard({ canEdit }: { canEdit: boolean }) {
  const [format, setFormat] = React.useState<AccountPasswordFormat | null>(null);
  const [unavailable, setUnavailable] = React.useState(false);
  const [err, setErr] = React.useState<unknown>(null);
  const [changes, setChanges] = React.useState<AccountPasswordFormatChange[] | null>(null);
  const [editing, setEditing] = React.useState(false);

  const load = React.useCallback(() => {
    setErr(null);
    setUnavailable(false);
    api
      .get<AccountPasswordFormat>("/account-password-settings/")
      .then((f) => (isFormat(f) ? setFormat(f) : setUnavailable(true)))
      .catch(setErr);
    api
      .get<{ changes?: AccountPasswordFormatChange[] }>("/account-password-settings/changes")
      .then((m) => setChanges(Array.isArray(m?.changes) ? m.changes : []))
      .catch(() => setChanges([]));
  }, []);
  React.useEffect(load, [load]);

  const style = format ? styleOf(format, format.password_style) : undefined;
  const example = React.useMemo(
    () => (style && format ? examplePassword(style.alphabet, format.password_length) : ""),
    [style, format],
  );

  return (
    <Card>
      <CardHeader>
        <div className="space-y-0.5">
          <CardTitle>Generated passwords</CardTitle>
          <CardDescription>
            What a password looks like when you choose &ldquo;Generate&rdquo;. Existing passwords are not changed.
          </CardDescription>
        </div>
        {canEdit && format && (
          <Button size="sm" variant="secondary" onClick={() => setEditing(true)}>
            <Pencil /> Change format
          </Button>
        )}
      </CardHeader>
      <CardBody className="space-y-4">
        {err ? (
          <div className="space-y-2">
            <ErrorBanner err={err} />
            <Button size="sm" variant="secondary" onClick={load}>
              <RefreshCw /> Try again
            </Button>
          </div>
        ) : unavailable ? (
          <p className="text-sm text-muted-foreground">This appliance does not report a generated-password format.</p>
        ) : !format ? (
          <Skeleton className="h-16" />
        ) : (
          <>
            <KeyValueGrid
              items={[
                { label: "Characters", value: style?.label ?? format.password_style },
                { label: "Length", value: `${format.password_length} characters` },
                {
                  label: "Looks like",
                  value: <span className="font-mono text-base tracking-wider" data-testid="password-format-example">{example}</span>,
                },
                {
                  label: "Chosen",
                  value: format.config_version === 0 || !format.updated_at
                    ? "Not yet: the defaults are in use"
                    : `${formatRelative(format.updated_at)}${format.updated_by ? ` by ${format.updated_by}` : ""}`,
                },
              ]}
            />
            {!canEdit && (
              <p className="text-xs text-muted-foreground">Your role can see the format but not change it.</p>
            )}
            {changes && changes.length > 0 && (
              <div className="space-y-2">
                <p className="inline-flex items-center gap-2 text-sm font-medium">
                  <History className="size-4" aria-hidden /> Recent changes
                </p>
                <Timeline
                  items={changes.slice(0, 5).map((c, i) => ({
                    key: `${c.changed_at}-${i}`,
                    title:
                      c.old_password_style && c.old_password_length
                        ? `${formatWords(format, c.old_password_style, c.old_password_length)} → ${formatWords(format, c.new_password_style, c.new_password_length)}`
                        : `Set to ${formatWords(format, c.new_password_style, c.new_password_length)}`,
                    when: formatRelative(c.changed_at),
                    body: [c.changed_by, c.change_reason && `“${c.change_reason}”`].filter(Boolean).join(" · "),
                    tone: "info" as const,
                  }))}
                />
              </div>
            )}
          </>
        )}
      </CardBody>
      {format && canEdit && (
        <PasswordFormatDialog
          open={editing}
          onOpenChange={setEditing}
          current={format}
          onSaved={load}
        />
      )}
    </Card>
  );
}

export function PasswordFormatDialog({
  open,
  onOpenChange,
  current,
  onSaved,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  current: AccountPasswordFormat;
  onSaved: () => void;
}) {
  const toast = useToast();
  const [styleKey, setStyleKey] = React.useState(current.password_style);
  const [length, setLength] = React.useState(current.password_length);
  const [reason, setReason] = React.useState("");
  const [busy, setBusy] = React.useState(false);
  const [err, setErr] = React.useState<unknown>(null);

  React.useEffect(() => {
    if (open) {
      setStyleKey(current.password_style);
      setLength(current.password_length);
      setReason("");
      setErr(null);
    }
  }, [open, current]);

  const style = styleOf(current, styleKey) ?? current.limits.styles[0];
  const min = style.min_length;
  const max = style.max_length ?? current.limits.max_length;
  // Switching to a style with a higher floor lifts the length to that floor rather than leaving an illegal value.
  React.useEffect(() => {
    setLength((n) => Math.min(max, Math.max(min, n)));
  }, [min, max]);

  const lengths = React.useMemo(() => {
    const out: number[] = [];
    for (let n = min; n <= max; n++) out.push(n);
    return out;
  }, [min, max]);
  const example = React.useMemo(() => examplePassword(style.alphabet, length), [style.alphabet, length]);
  const unchanged = styleKey === current.password_style && length === current.password_length;
  const reasonErr = reason === "" ? null : formatReasonProblem(reason);
  const bits = Math.floor(style.bits_per_char * length);

  async function submit() {
    const bad = formatReasonProblem(reason);
    if (bad) return setErr(new Error(bad));
    setBusy(true);
    setErr(null);
    try {
      const out = await api.put<{ notice?: string }>("/account-password-settings/", {
        password_style: styleKey,
        password_length: length,
        reason: reason.trim(),
      });
      toast.success("Password format changed", out?.notice ?? "It applies to the next password you generate.");
      onSaved();
      onOpenChange(false);
    } catch (e) {
      setErr(e);
    } finally {
      setBusy(false);
    }
  }

  return (
    <DialogForm
      open={open}
      onOpenChange={onOpenChange}
      title="Change the generated-password format"
      description="Only passwords generated after this change use the new format. Existing passwords keep working."
      submitLabel="Save format"
      busy={busy}
      error={err}
      disabled={unchanged || reason.trim().length < 4}
      onSubmit={submit}
    >
      <div role="radiogroup" aria-label="Characters" className="grid gap-3 sm:grid-cols-2">
        {current.limits.styles.map((s) => (
          <OptionCard
            key={s.key}
            name="password-style"
            value={s.key}
            checked={styleKey === s.key}
            onChange={() => setStyleKey(s.key)}
            title={s.label}
            description={`At least ${s.min_length} characters`}
          />
        ))}
      </div>
      <Field label="Length" hint={`Between ${min} and ${max} characters for this style.`}>
        <Select aria-label="Length" value={length} onChange={(e) => setLength(Number(e.target.value))}>
          {lengths.map((n) => (
            <option key={n} value={n}>
              {n} characters
            </option>
          ))}
        </Select>
      </Field>
      <div className="rounded-md border border-border bg-surface px-3 py-2 text-sm">
        Generated passwords will look like:{" "}
        <span className="font-mono text-base font-semibold tracking-wider" data-testid="password-format-preview">
          {example}
        </span>
        <span className="block text-xs text-muted-foreground">
          An example of the shape only (about {bits} bits). Easily confused characters (0/O, 1/I/l) are never used.
        </span>
      </div>
      {unchanged && <Callout tone="neutral">This is the current format. Choose something different to change it.</Callout>}
      <Field label="Reason for the change" error={reasonErr ?? undefined} hint="Recorded in the format history." required>
        <Input value={reason} maxLength={500} onChange={(e) => setReason(e.target.value)} placeholder="Clients type these on a keypad" />
      </Field>
    </DialogForm>
  );
}
